//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	using Neo.ApplicationFramework.Interfaces;
	
	
	public partial class FunctionKeys : Neo.ApplicationFramework.Tools.FunctionKey.FunctionKeyManager
	{
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F1;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F2;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F3;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F4;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F5;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F6;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F7;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F8;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F9;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F10;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F11;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F12;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F13;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F14;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F15;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F16;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F17;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F18;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F19;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F20;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F21;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F22;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F23;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F24;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext m_S1手動;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext m_S2手動;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext m_手動選擇;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext m_S3手動;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext m_S4手動;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext m_基礎畫面;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext m_S5手動;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext m_S6手動;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext m_S7手動;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext m_S8手動;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext m_S9手動;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext m_主頁;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext m_S10手動;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext m_S11手動;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext m_測試;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext m_時間1;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext m_時間2;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext m_工作站選擇;
		
		public FunctionKeys()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F1
		{
			get
			{
				return this.m_F1;
			}
			set
			{
				this.m_F1 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F2
		{
			get
			{
				return this.m_F2;
			}
			set
			{
				this.m_F2 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F3
		{
			get
			{
				return this.m_F3;
			}
			set
			{
				this.m_F3 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F4
		{
			get
			{
				return this.m_F4;
			}
			set
			{
				this.m_F4 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F5
		{
			get
			{
				return this.m_F5;
			}
			set
			{
				this.m_F5 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F6
		{
			get
			{
				return this.m_F6;
			}
			set
			{
				this.m_F6 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F7
		{
			get
			{
				return this.m_F7;
			}
			set
			{
				this.m_F7 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F8
		{
			get
			{
				return this.m_F8;
			}
			set
			{
				this.m_F8 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F9
		{
			get
			{
				return this.m_F9;
			}
			set
			{
				this.m_F9 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F10
		{
			get
			{
				return this.m_F10;
			}
			set
			{
				this.m_F10 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F11
		{
			get
			{
				return this.m_F11;
			}
			set
			{
				this.m_F11 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F12
		{
			get
			{
				return this.m_F12;
			}
			set
			{
				this.m_F12 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F13
		{
			get
			{
				return this.m_F13;
			}
			set
			{
				this.m_F13 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F14
		{
			get
			{
				return this.m_F14;
			}
			set
			{
				this.m_F14 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F15
		{
			get
			{
				return this.m_F15;
			}
			set
			{
				this.m_F15 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F16
		{
			get
			{
				return this.m_F16;
			}
			set
			{
				this.m_F16 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F17
		{
			get
			{
				return this.m_F17;
			}
			set
			{
				this.m_F17 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F18
		{
			get
			{
				return this.m_F18;
			}
			set
			{
				this.m_F18 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F19
		{
			get
			{
				return this.m_F19;
			}
			set
			{
				this.m_F19 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F20
		{
			get
			{
				return this.m_F20;
			}
			set
			{
				this.m_F20 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F21
		{
			get
			{
				return this.m_F21;
			}
			set
			{
				this.m_F21 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F22
		{
			get
			{
				return this.m_F22;
			}
			set
			{
				this.m_F22 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F23
		{
			get
			{
				return this.m_F23;
			}
			set
			{
				this.m_F23 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F24
		{
			get
			{
				return this.m_F24;
			}
			set
			{
				this.m_F24 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext S1手動
		{
			get
			{
				return this.m_S1手動;
			}
			set
			{
				this.m_S1手動 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext S2手動
		{
			get
			{
				return this.m_S2手動;
			}
			set
			{
				this.m_S2手動 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext 手動選擇
		{
			get
			{
				return this.m_手動選擇;
			}
			set
			{
				this.m_手動選擇 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext S3手動
		{
			get
			{
				return this.m_S3手動;
			}
			set
			{
				this.m_S3手動 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext S4手動
		{
			get
			{
				return this.m_S4手動;
			}
			set
			{
				this.m_S4手動 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext 基礎畫面
		{
			get
			{
				return this.m_基礎畫面;
			}
			set
			{
				this.m_基礎畫面 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext S5手動
		{
			get
			{
				return this.m_S5手動;
			}
			set
			{
				this.m_S5手動 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext S6手動
		{
			get
			{
				return this.m_S6手動;
			}
			set
			{
				this.m_S6手動 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext S7手動
		{
			get
			{
				return this.m_S7手動;
			}
			set
			{
				this.m_S7手動 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext S8手動
		{
			get
			{
				return this.m_S8手動;
			}
			set
			{
				this.m_S8手動 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext S9手動
		{
			get
			{
				return this.m_S9手動;
			}
			set
			{
				this.m_S9手動 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext 主頁
		{
			get
			{
				return this.m_主頁;
			}
			set
			{
				this.m_主頁 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext S10手動
		{
			get
			{
				return this.m_S10手動;
			}
			set
			{
				this.m_S10手動 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext S11手動
		{
			get
			{
				return this.m_S11手動;
			}
			set
			{
				this.m_S11手動 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext 測試
		{
			get
			{
				return this.m_測試;
			}
			set
			{
				this.m_測試 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext 時間1
		{
			get
			{
				return this.m_時間1;
			}
			set
			{
				this.m_時間1 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext 時間2
		{
			get
			{
				return this.m_時間2;
			}
			set
			{
				this.m_時間2 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext 工作站選擇
		{
			get
			{
				return this.m_工作站選擇;
			}
			set
			{
				this.m_工作站選擇 = value;
			}
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public override void ConnectDataBindings()
		{
			base.ConnectDataBindings();
		}
		
		private void InitializeObjectCreations()
		{
			this.F1 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F2 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F3 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F4 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F5 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F6 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F7 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F8 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F9 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F10 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F11 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F12 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F13 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F14 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F15 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F16 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F17 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F18 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F19 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F20 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F21 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F22 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F23 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.F24 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey();
			this.S1手動 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext();
			this.S2手動 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext();
			this.手動選擇 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext();
			this.S3手動 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext();
			this.S4手動 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext();
			this.基礎畫面 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext();
			this.S5手動 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext();
			this.S6手動 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext();
			this.S7手動 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext();
			this.S8手動 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext();
			this.S9手動 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext();
			this.主頁 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext();
			this.S10手動 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext();
			this.S11手動 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext();
			this.測試 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext();
			this.時間1 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext();
			this.時間2 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext();
			this.工作站選擇 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext();
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F2)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F3)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F4)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F5)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F6)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F7)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F8)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F9)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F10)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F11)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F12)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F13)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F14)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F15)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F16)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F17)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F18)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F19)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F20)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F21)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F22)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F23)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F24)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this.F1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F2)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F3)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F4)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F5)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F6)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F7)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F8)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F9)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F10)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F11)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F12)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F13)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F14)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F15)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F16)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F17)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F18)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F19)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F20)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F21)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F22)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F23)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F24)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.F1.KeyCode = System.Windows.Forms.Keys.F1;
			this.F1.Name = "F1";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf1 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F1.SecurityProperties = securitypropertiescf1;
			this.F2.KeyCode = System.Windows.Forms.Keys.F2;
			this.F2.Name = "F2";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf2 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F2.SecurityProperties = securitypropertiescf2;
			this.F3.KeyCode = System.Windows.Forms.Keys.F3;
			this.F3.Name = "F3";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf3 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F3.SecurityProperties = securitypropertiescf3;
			this.F4.KeyCode = System.Windows.Forms.Keys.F4;
			this.F4.Name = "F4";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf4 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F4.SecurityProperties = securitypropertiescf4;
			this.F5.KeyCode = System.Windows.Forms.Keys.F5;
			this.F5.Name = "F5";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf5 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F5.SecurityProperties = securitypropertiescf5;
			this.F6.KeyCode = System.Windows.Forms.Keys.F6;
			this.F6.Name = "F6";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf6 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F6.SecurityProperties = securitypropertiescf6;
			this.F7.KeyCode = System.Windows.Forms.Keys.F7;
			this.F7.Name = "F7";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf7 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F7.SecurityProperties = securitypropertiescf7;
			this.F8.KeyCode = System.Windows.Forms.Keys.F8;
			this.F8.Name = "F8";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf8 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F8.SecurityProperties = securitypropertiescf8;
			this.F9.KeyCode = System.Windows.Forms.Keys.F9;
			this.F9.Name = "F9";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf9 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F9.SecurityProperties = securitypropertiescf9;
			this.F10.KeyCode = System.Windows.Forms.Keys.F10;
			this.F10.Name = "F10";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf10 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F10.SecurityProperties = securitypropertiescf10;
			this.F11.KeyCode = System.Windows.Forms.Keys.F11;
			this.F11.Name = "F11";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf11 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F11.SecurityProperties = securitypropertiescf11;
			this.F12.KeyCode = System.Windows.Forms.Keys.F12;
			this.F12.Name = "F12";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf12 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F12.SecurityProperties = securitypropertiescf12;
			this.F13.KeyCode = System.Windows.Forms.Keys.F13;
			this.F13.Name = "F13";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf13 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F13.SecurityProperties = securitypropertiescf13;
			this.F14.KeyCode = System.Windows.Forms.Keys.F14;
			this.F14.Name = "F14";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf14 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F14.SecurityProperties = securitypropertiescf14;
			this.F15.KeyCode = System.Windows.Forms.Keys.F15;
			this.F15.Name = "F15";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf15 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F15.SecurityProperties = securitypropertiescf15;
			this.F16.KeyCode = System.Windows.Forms.Keys.F16;
			this.F16.Name = "F16";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf16 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F16.SecurityProperties = securitypropertiescf16;
			this.F17.KeyCode = System.Windows.Forms.Keys.F17;
			this.F17.Name = "F17";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf17 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F17.SecurityProperties = securitypropertiescf17;
			this.F18.KeyCode = System.Windows.Forms.Keys.F18;
			this.F18.Name = "F18";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf18 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F18.SecurityProperties = securitypropertiescf18;
			this.F19.KeyCode = System.Windows.Forms.Keys.F19;
			this.F19.Name = "F19";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf19 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F19.SecurityProperties = securitypropertiescf19;
			this.F20.KeyCode = System.Windows.Forms.Keys.F20;
			this.F20.Name = "F20";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf20 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F20.SecurityProperties = securitypropertiescf20;
			this.F21.KeyCode = System.Windows.Forms.Keys.F21;
			this.F21.Name = "F21";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf21 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F21.SecurityProperties = securitypropertiescf21;
			this.F22.KeyCode = System.Windows.Forms.Keys.F22;
			this.F22.Name = "F22";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf22 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F22.SecurityProperties = securitypropertiescf22;
			this.F23.KeyCode = System.Windows.Forms.Keys.F23;
			this.F23.Name = "F23";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf23 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F23.SecurityProperties = securitypropertiescf23;
			this.F24.KeyCode = System.Windows.Forms.Keys.F24;
			this.F24.Name = "F24";
			Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF securitypropertiescf24 = new Neo.ApplicationFramework.Common.Security.SecurityPropertiesCF();
			this.F24.SecurityProperties = securitypropertiescf24;
			this.GlobalFunctionKeys.Add(this.F1);
			this.GlobalFunctionKeys.Add(this.F2);
			this.GlobalFunctionKeys.Add(this.F3);
			this.GlobalFunctionKeys.Add(this.F4);
			this.GlobalFunctionKeys.Add(this.F5);
			this.GlobalFunctionKeys.Add(this.F6);
			this.GlobalFunctionKeys.Add(this.F7);
			this.GlobalFunctionKeys.Add(this.F8);
			this.GlobalFunctionKeys.Add(this.F9);
			this.GlobalFunctionKeys.Add(this.F10);
			this.GlobalFunctionKeys.Add(this.F11);
			this.GlobalFunctionKeys.Add(this.F12);
			this.GlobalFunctionKeys.Add(this.F13);
			this.GlobalFunctionKeys.Add(this.F14);
			this.GlobalFunctionKeys.Add(this.F15);
			this.GlobalFunctionKeys.Add(this.F16);
			this.GlobalFunctionKeys.Add(this.F17);
			this.GlobalFunctionKeys.Add(this.F18);
			this.GlobalFunctionKeys.Add(this.F19);
			this.GlobalFunctionKeys.Add(this.F20);
			this.GlobalFunctionKeys.Add(this.F21);
			this.GlobalFunctionKeys.Add(this.F22);
			this.GlobalFunctionKeys.Add(this.F23);
			this.GlobalFunctionKeys.Add(this.F24);
			this.S1手動.Name = "S1手動";
			this.S1手動.ScreenName = "S1手動";
			this.S2手動.Name = "S2手動";
			this.S2手動.ScreenName = "S2手動";
			this.手動選擇.Name = "手動選擇";
			this.手動選擇.ScreenName = "手動選擇";
			this.S3手動.Name = "S3手動";
			this.S3手動.ScreenName = "S3手動";
			this.S4手動.Name = "S4手動";
			this.S4手動.ScreenName = "S4手動";
			this.基礎畫面.Name = "基礎畫面";
			this.基礎畫面.ScreenName = "基礎畫面";
			this.S5手動.Name = "S5手動";
			this.S5手動.ScreenName = "S5手動";
			this.S6手動.Name = "S6手動";
			this.S6手動.ScreenName = "S6手動";
			this.S7手動.Name = "S7手動";
			this.S7手動.ScreenName = "S7手動";
			this.S8手動.Name = "S8手動";
			this.S8手動.ScreenName = "S8手動";
			this.S9手動.Name = "S9手動";
			this.S9手動.ScreenName = "S9手動";
			this.主頁.Name = "主頁";
			this.主頁.ScreenName = "主頁";
			this.S10手動.Name = "S10手動";
			this.S10手動.ScreenName = "S10手動";
			this.S11手動.Name = "S11手動";
			this.S11手動.ScreenName = "S11手動";
			this.測試.Name = "測試";
			this.測試.ScreenName = "測試";
			this.時間1.Name = "時間1";
			this.時間1.ScreenName = "時間1";
			this.時間2.Name = "時間2";
			this.時間2.ScreenName = "時間2";
			this.工作站選擇.Name = "工作站選擇";
			this.工作站選擇.ScreenName = "工作站選擇";
			this.LocalFunctionKeys.Add(this.S1手動);
			this.LocalFunctionKeys.Add(this.S2手動);
			this.LocalFunctionKeys.Add(this.手動選擇);
			this.LocalFunctionKeys.Add(this.S3手動);
			this.LocalFunctionKeys.Add(this.S4手動);
			this.LocalFunctionKeys.Add(this.基礎畫面);
			this.LocalFunctionKeys.Add(this.S5手動);
			this.LocalFunctionKeys.Add(this.S6手動);
			this.LocalFunctionKeys.Add(this.S7手動);
			this.LocalFunctionKeys.Add(this.S8手動);
			this.LocalFunctionKeys.Add(this.S9手動);
			this.LocalFunctionKeys.Add(this.主頁);
			this.LocalFunctionKeys.Add(this.S10手動);
			this.LocalFunctionKeys.Add(this.S11手動);
			this.LocalFunctionKeys.Add(this.測試);
			this.LocalFunctionKeys.Add(this.時間1);
			this.LocalFunctionKeys.Add(this.時間2);
			this.LocalFunctionKeys.Add(this.工作站選擇);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(FunctionKeys));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected override void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
			base.ApplyLanguage();
		}
	}
}
