//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class S11手動 : Neo.ApplicationFramework.Controls.Controls.Form {
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button1;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button8;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_bPG_Main;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button5;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private bool m_Initialized_S11手動;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf1;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf2;
        
        public S11手動() {
            this.InitializeComponent();
            this.m_Button1.MouseDown += new System.EventHandler(this.m_Button1_Action_PreviewMouseDown);
            this.m_Button1.MouseUp += new System.EventHandler(this.m_Button1_Action_PreviewMouseUp);
            this.m_Button1.MouseLeave += new System.EventHandler(this.m_Button1_Action_MouseLeave);
            this.m_Button8.MouseDown += new System.EventHandler(this.m_Button8_Action_PreviewMouseDown);
            this.m_Button8.MouseUp += new System.EventHandler(this.m_Button8_Action_PreviewMouseUp);
            this.m_Button8.MouseLeave += new System.EventHandler(this.m_Button8_Action_MouseLeave);
            this.m_bPG_Main.Click += new System.EventHandler(this.m_bPG_Main_Action_Click);
            this.m_Button5.Click += new System.EventHandler(this.m_Button5_Action_Click);
            this.m_Button.Click += new System.EventHandler(this.m_Button_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button8);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter bPG_Main {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_bPG_Main);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        private void InitializeComponent() {
            this.brushdynamicsconvertercf2 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            this.brushdynamicsconvertercf1 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval1 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval2 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval3 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval4 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_Line = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Button1 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button8 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_bPG_Main = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button5 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_bPG_Main)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            this.SuspendLayout();
            // 
            // S11手動
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_Line
            // 
            this.m_Line.BlinkDynamicsValue = false;
            this.m_Line.EnabledDynamicsValue = true;
            this.m_Line.Fill = null;
            this.m_Line.Name = "m_Line";
            this.m_Line.ScreenOwnerName = "S11手動";
            this.m_Line.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line.VisibleDynamicsValue = true;
            this.m_Line.X1 = 2;
            this.m_Line.X2 = 820;
            this.m_Line.Y1 = 66;
            this.m_Line.Y2 = 67;
            // 
            // m_Button1
            // 
            this.m_Button1.BlinkDynamicsValue = false;
            this.m_Button1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            brushdynamicsconvertercf1.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval1.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval2.End = 1D;
            brushcfinterval2.Start = 1D;
            brushcfinterval2.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(183)))), ((int)(((byte)(117)))), ((int)(((byte)(64))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval1);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval2);
            this.m_Button1.EnabledDynamicsValue = true;
            this.m_Button1.FontFamily = "新細明體";
            this.m_Button1.FontSizePixels = 30;
            this.m_Button1.ForceTransparency = true;
            this.m_Button1.Height = 100;
            this.m_Button1.IndicatorMargin = null;
            this.m_Button1.Left = 2;
            this.m_Button1.MultiLine = true;
            this.m_Button1.Name = "m_Button1";
            this.m_Button1.RequiresTransparency = true;
            this.m_Button1.ScreenOwnerName = "S11手動";
            this.m_Button1.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button1.TextHeight = 72;
            this.m_Button1.TextValue = 0D;
            this.m_Button1.TextWidth = 120;
            this.m_Button1.Top = 69;
            this.m_Button1.Value = 0D;
            this.m_Button1.VisibleDynamicsValue = true;
            this.m_Button1.VisualPropertiesHashCode = 1197681854;
            this.m_Button1.Width = 130;
            // 
            // m_Button8
            // 
            this.m_Button8.BlinkDynamicsValue = false;
            this.m_Button8.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button8.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            brushdynamicsconvertercf2.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval3.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval4.End = 1D;
            brushcfinterval4.Start = 1D;
            brushcfinterval4.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(183)))), ((int)(((byte)(117)))), ((int)(((byte)(64))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf2.BrushIntervalMapper.Intervals.Add(brushcfinterval3);
            brushdynamicsconvertercf2.BrushIntervalMapper.Intervals.Add(brushcfinterval4);
            this.m_Button8.EnabledDynamicsValue = true;
            this.m_Button8.FontFamily = "新細明體";
            this.m_Button8.FontSizePixels = 30;
            this.m_Button8.ForceTransparency = true;
            this.m_Button8.Height = 100;
            this.m_Button8.IndicatorMargin = null;
            this.m_Button8.Left = 669;
            this.m_Button8.MultiLine = true;
            this.m_Button8.Name = "m_Button8";
            this.m_Button8.RequiresTransparency = true;
            this.m_Button8.ScreenOwnerName = "S11手動";
            this.m_Button8.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_Button8.TextHeight = 72;
            this.m_Button8.TextValue = 0D;
            this.m_Button8.TextWidth = 120;
            this.m_Button8.Top = 379;
            this.m_Button8.Value = 0D;
            this.m_Button8.VisibleDynamicsValue = true;
            this.m_Button8.VisualPropertiesHashCode = 1405317454;
            this.m_Button8.Width = 130;
            // 
            // m_bPG_Main
            // 
            this.m_bPG_Main.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_bPG_Main.BlinkDynamicsValue = false;
            this.m_bPG_Main.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(216)))), ((int)(((byte)(230))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_bPG_Main.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_bPG_Main.EnabledDynamicsValue = true;
            this.m_bPG_Main.FontFamily = "新細明體";
            this.m_bPG_Main.FontSizePixels = 40;
            this.m_bPG_Main.ForceTransparency = true;
            this.m_bPG_Main.Height = 66;
            this.m_bPG_Main.IndicatorMargin = null;
            this.m_bPG_Main.Left = 1;
            this.m_bPG_Main.Name = "m_bPG_Main";
            this.m_bPG_Main.RequiresTransparency = true;
            this.m_bPG_Main.ScreenOwnerName = "S11手動";
            this.m_bPG_Main.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_bPG_Main.TextHeight = 48;
            this.m_bPG_Main.TextValue = 0D;
            this.m_bPG_Main.TextWidth = 90;
            this.m_bPG_Main.Top = -1;
            this.m_bPG_Main.Value = 0D;
            this.m_bPG_Main.VisibleDynamicsValue = true;
            this.m_bPG_Main.VisualPropertiesHashCode = -1250412459;
            this.m_bPG_Main.Width = 100;
            // 
            // m_Button5
            // 
            this.m_Button5.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(216)))), ((int)(((byte)(230))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button5.BlinkDynamicsValue = false;
            this.m_Button5.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(216)))), ((int)(((byte)(230))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button5.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button5.EnabledDynamicsValue = true;
            this.m_Button5.FontFamily = "新細明體";
            this.m_Button5.FontSizePixels = 40;
            this.m_Button5.ForceTransparency = true;
            this.m_Button5.Height = 66;
            this.m_Button5.IndicatorMargin = null;
            this.m_Button5.Left = 106;
            this.m_Button5.MultiLine = true;
            this.m_Button5.Name = "m_Button5";
            this.m_Button5.RequiresTransparency = true;
            this.m_Button5.ScreenOwnerName = "S11手動";
            this.m_Button5.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_Button5.TextHeight = 48;
            this.m_Button5.TextValue = 0D;
            this.m_Button5.TextWidth = 90;
            this.m_Button5.Top = 0;
            this.m_Button5.Value = 0D;
            this.m_Button5.VisibleDynamicsValue = true;
            this.m_Button5.VisualPropertiesHashCode = -200374946;
            this.m_Button5.Width = 100;
            // 
            // m_Button
            // 
            this.m_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(216)))), ((int)(((byte)(230))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontFamily = "新細明體";
            this.m_Button.FontSizePixels = 40;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Height = 66;
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Left = 211;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "S11手動";
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper5;
            this.m_Button.TextHeight = 48;
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 90;
            this.m_Button.Top = 0;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = -1250412459;
            this.m_Button.Width = 100;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "S11手動";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_S11手動 = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_S11手動) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Line);
            this.DrawingPrimitives.Add(this.m_Button1);
            this.DrawingPrimitives.Add(this.m_Button8);
            this.DrawingPrimitives.Add(this.m_bPG_Main);
            this.DrawingPrimitives.Add(this.m_Button5);
            this.DrawingPrimitives.Add(this.m_Button);
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_bPG_Main)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
        }
        
        private void m_Button1_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button1", "MouseDown", "Set Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.S11_JigReject_PB.SetTag();
        }
        
        private void m_Button1_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button1", "MouseUp", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.S11_JigReject_PB.ResetTag();
        }
        
        private void m_Button1_Action_MouseLeave(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button1", "MouseLeave", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.S11_JigReject_PB.ResetTag();
        }
        
        private void m_Button8_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button8", "MouseDown", "Set Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Index_PB.SetTag();
        }
        
        private void m_Button8_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button8", "MouseUp", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Index_PB.ResetTag();
        }
        
        private void m_Button8_Action_MouseLeave(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button8", "MouseLeave", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Index_PB.ResetTag();
        }
        
        private void m_bPG_Main_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bPG_Main", "Click", "Show Screen", "主頁", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.主頁.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bPG_Main", "Click", "Set Tag", "Tags.AutoStatus", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.AutoStatus.SetTag();
        }
        
        private void m_Button5_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button5", "Click", "Show Screen", "手動選擇", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.手動選擇.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button5", "Click", "Reset Tag", "Tags.AutoStatus", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.AutoStatus.ResetTag();
        }
        
        private void m_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Show Screen", "測試", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.測試.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Set Tag", "Tags.AutoStatus", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.AutoStatus.SetTag();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(S11手動));
            this.m_Button1.Text = resources.GetText("S11手動.Button1.Text", "治具上\r\n夾持退出");
            this.m_Button8.Text = resources.GetText("S11手動.Button8.Text", "轉盤\r\n運轉");
            this.m_bPG_Main.Text = resources.GetText("S11手動.bPG_Main.Text", "主頁");
            this.m_Button5.Text = resources.GetText("S11手動.Button5.Text", "S11");
            this.m_Button.Text = resources.GetText("S11手動.Button.Text", "測試");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_S11手動) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Index_PB"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button8.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Background", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Index_RY"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf2);
            this.m_Button8.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.S11_JigReject_PB"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button1.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Background", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.S11_JigReject_SOL"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf1);
            this.m_Button1.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
        }
    }
}
