//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class 測試 : Neo.ApplicationFramework.Controls.Controls.Form {
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button2;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button3;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button4;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button5;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button6;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button7;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button9;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button10;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button11;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button12;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button13;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button8;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button14;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button15;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Group;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_bPG_Main;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button1;
        
        private bool m_Initialized_測試;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf1;
        
        public 測試() {
            this.InitializeComponent();
            this.m_Button2.MouseDown += new System.EventHandler(this.m_Button2_Action_PreviewMouseDown);
            this.m_Button2.MouseUp += new System.EventHandler(this.m_Button2_Action_PreviewMouseUp);
            this.m_Button2.MouseLeave += new System.EventHandler(this.m_Button2_Action_MouseLeave);
            this.m_Button3.MouseDown += new System.EventHandler(this.m_Button3_Action_PreviewMouseDown);
            this.m_Button3.MouseUp += new System.EventHandler(this.m_Button3_Action_PreviewMouseUp);
            this.m_Button3.MouseLeave += new System.EventHandler(this.m_Button3_Action_MouseLeave);
            this.m_Button4.MouseDown += new System.EventHandler(this.m_Button4_Action_PreviewMouseDown);
            this.m_Button4.MouseUp += new System.EventHandler(this.m_Button4_Action_PreviewMouseUp);
            this.m_Button4.MouseLeave += new System.EventHandler(this.m_Button4_Action_MouseLeave);
            this.m_Button5.MouseDown += new System.EventHandler(this.m_Button5_Action_PreviewMouseDown);
            this.m_Button5.MouseUp += new System.EventHandler(this.m_Button5_Action_PreviewMouseUp);
            this.m_Button5.MouseLeave += new System.EventHandler(this.m_Button5_Action_MouseLeave);
            this.m_Button6.MouseDown += new System.EventHandler(this.m_Button6_Action_PreviewMouseDown);
            this.m_Button6.MouseUp += new System.EventHandler(this.m_Button6_Action_PreviewMouseUp);
            this.m_Button6.MouseLeave += new System.EventHandler(this.m_Button6_Action_MouseLeave);
            this.m_Button7.MouseDown += new System.EventHandler(this.m_Button7_Action_PreviewMouseDown);
            this.m_Button7.MouseUp += new System.EventHandler(this.m_Button7_Action_PreviewMouseUp);
            this.m_Button7.MouseLeave += new System.EventHandler(this.m_Button7_Action_MouseLeave);
            this.m_Button9.MouseDown += new System.EventHandler(this.m_Button9_Action_PreviewMouseDown);
            this.m_Button9.MouseUp += new System.EventHandler(this.m_Button9_Action_PreviewMouseUp);
            this.m_Button9.MouseLeave += new System.EventHandler(this.m_Button9_Action_MouseLeave);
            this.m_Button10.MouseDown += new System.EventHandler(this.m_Button10_Action_PreviewMouseDown);
            this.m_Button10.MouseUp += new System.EventHandler(this.m_Button10_Action_PreviewMouseUp);
            this.m_Button10.MouseLeave += new System.EventHandler(this.m_Button10_Action_MouseLeave);
            this.m_Button11.MouseDown += new System.EventHandler(this.m_Button11_Action_PreviewMouseDown);
            this.m_Button11.MouseUp += new System.EventHandler(this.m_Button11_Action_PreviewMouseUp);
            this.m_Button11.MouseLeave += new System.EventHandler(this.m_Button11_Action_MouseLeave);
            this.m_Button12.MouseDown += new System.EventHandler(this.m_Button12_Action_PreviewMouseDown);
            this.m_Button12.MouseUp += new System.EventHandler(this.m_Button12_Action_PreviewMouseUp);
            this.m_Button12.MouseLeave += new System.EventHandler(this.m_Button12_Action_MouseLeave);
            this.m_Button13.MouseDown += new System.EventHandler(this.m_Button13_Action_PreviewMouseDown);
            this.m_Button13.MouseUp += new System.EventHandler(this.m_Button13_Action_PreviewMouseUp);
            this.m_Button13.MouseLeave += new System.EventHandler(this.m_Button13_Action_MouseLeave);
            this.m_Button8.MouseDown += new System.EventHandler(this.m_Button8_Action_PreviewMouseDown);
            this.m_Button8.MouseUp += new System.EventHandler(this.m_Button8_Action_PreviewMouseUp);
            this.m_Button8.MouseLeave += new System.EventHandler(this.m_Button8_Action_MouseLeave);
            this.m_Button14.Click += new System.EventHandler(this.m_Button14_Action_Click);
            this.m_Button15.Click += new System.EventHandler(this.m_Button15_Action_Click);
            this.m_bPG_Main.Click += new System.EventHandler(this.m_bPG_Main_Action_Click);
            this.m_Button.Click += new System.EventHandler(this.m_Button_Action_Click);
            this.m_Button1.Click += new System.EventHandler(this.m_Button1_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button7 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button7);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button9 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button9);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button10 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button10);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button11 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button11);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button12 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button12);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button13 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button13);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Group {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Group);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button8);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button14 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button14);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button15 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button15);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter bPG_Main {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_bPG_Main);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button1);
            }
        }
        
        private void InitializeComponent() {
            this.brushdynamicsconvertercf1 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper6 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper7 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper8 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper9 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper10 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper11 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper12 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval1 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval2 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper13 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF stringintervalmappercf1 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalMapperCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf1 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF stringintervalcf2 = new Neo.ApplicationFramework.Common.Dynamics.StringIntervalCF();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper14 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper15 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper16 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper17 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_Line = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Button2 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button3 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button4 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button5 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button6 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button7 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button9 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button10 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button11 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button12 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button13 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button8 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button14 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button15 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Group = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_bPG_Main = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button1 = new Neo.ApplicationFramework.Controls.Controls.Button();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button9)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button10)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button11)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button12)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button13)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button14)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button15)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_bPG_Main)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).BeginInit();
            this.SuspendLayout();
            // 
            // 測試
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_Line
            // 
            this.m_Line.BlinkDynamicsValue = false;
            this.m_Line.EnabledDynamicsValue = true;
            this.m_Line.Fill = null;
            this.m_Line.Name = "m_Line";
            this.m_Line.ScreenOwnerName = "測試";
            this.m_Line.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line.VisibleDynamicsValue = true;
            this.m_Line.X1 = 1;
            this.m_Line.X2 = 800;
            this.m_Line.Y1 = 72;
            this.m_Line.Y2 = 71;
            // 
            // m_Button2
            // 
            this.m_Button2.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button2.BlinkDynamicsValue = false;
            this.m_Button2.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button2.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button2.EnabledDynamicsValue = true;
            this.m_Button2.FontFamily = "新細明體";
            this.m_Button2.FontSizePixels = 40;
            this.m_Button2.ForceTransparency = true;
            this.m_Button2.Height = 100;
            this.m_Button2.IndicatorMargin = null;
            this.m_Button2.Left = 2;
            this.m_Button2.Name = "m_Button2";
            this.m_Button2.RequiresTransparency = true;
            this.m_Button2.ScreenOwnerName = "測試";
            this.m_Button2.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button2.TextHeight = 48;
            this.m_Button2.TextValue = 0D;
            this.m_Button2.TextWidth = 182;
            this.m_Button2.Top = 75;
            this.m_Button2.Value = 0D;
            this.m_Button2.VisibleDynamicsValue = true;
            this.m_Button2.VisualPropertiesHashCode = -1757690157;
            this.m_Button2.Width = 192;
            // 
            // m_Button3
            // 
            this.m_Button3.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button3.BlinkDynamicsValue = false;
            this.m_Button3.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button3.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button3.EnabledDynamicsValue = true;
            this.m_Button3.FontFamily = "新細明體";
            this.m_Button3.FontSizePixels = 40;
            this.m_Button3.ForceTransparency = true;
            this.m_Button3.Height = 100;
            this.m_Button3.IndicatorMargin = null;
            this.m_Button3.Left = 196;
            this.m_Button3.Name = "m_Button3";
            this.m_Button3.RequiresTransparency = true;
            this.m_Button3.ScreenOwnerName = "測試";
            this.m_Button3.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_Button3.TextHeight = 48;
            this.m_Button3.TextValue = 0D;
            this.m_Button3.TextWidth = 182;
            this.m_Button3.Top = 176;
            this.m_Button3.Value = 0D;
            this.m_Button3.VisibleDynamicsValue = true;
            this.m_Button3.VisualPropertiesHashCode = -1757690157;
            this.m_Button3.Width = 192;
            // 
            // m_Button4
            // 
            this.m_Button4.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button4.BlinkDynamicsValue = false;
            this.m_Button4.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button4.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button4.EnabledDynamicsValue = true;
            this.m_Button4.FontFamily = "新細明體";
            this.m_Button4.FontSizePixels = 40;
            this.m_Button4.ForceTransparency = true;
            this.m_Button4.Height = 100;
            this.m_Button4.IndicatorMargin = null;
            this.m_Button4.Left = 390;
            this.m_Button4.Name = "m_Button4";
            this.m_Button4.RequiresTransparency = true;
            this.m_Button4.ScreenOwnerName = "測試";
            this.m_Button4.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_Button4.TextHeight = 48;
            this.m_Button4.TextValue = 0D;
            this.m_Button4.TextWidth = 182;
            this.m_Button4.Top = 277;
            this.m_Button4.Value = 0D;
            this.m_Button4.VisibleDynamicsValue = true;
            this.m_Button4.VisualPropertiesHashCode = -1757690157;
            this.m_Button4.Width = 192;
            // 
            // m_Button5
            // 
            this.m_Button5.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button5.BlinkDynamicsValue = false;
            this.m_Button5.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button5.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button5.EnabledDynamicsValue = true;
            this.m_Button5.FontFamily = "新細明體";
            this.m_Button5.FontSizePixels = 40;
            this.m_Button5.ForceTransparency = true;
            this.m_Button5.Height = 100;
            this.m_Button5.IndicatorMargin = null;
            this.m_Button5.Left = 196;
            this.m_Button5.Name = "m_Button5";
            this.m_Button5.RequiresTransparency = true;
            this.m_Button5.ScreenOwnerName = "測試";
            this.m_Button5.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_Button5.TextHeight = 48;
            this.m_Button5.TextValue = 0D;
            this.m_Button5.TextWidth = 182;
            this.m_Button5.Top = 75;
            this.m_Button5.Value = 0D;
            this.m_Button5.VisibleDynamicsValue = true;
            this.m_Button5.VisualPropertiesHashCode = -1757690157;
            this.m_Button5.Width = 192;
            // 
            // m_Button6
            // 
            this.m_Button6.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button6.BlinkDynamicsValue = false;
            this.m_Button6.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button6.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button6.EnabledDynamicsValue = true;
            this.m_Button6.FontFamily = "新細明體";
            this.m_Button6.FontSizePixels = 40;
            this.m_Button6.ForceTransparency = true;
            this.m_Button6.Height = 100;
            this.m_Button6.IndicatorMargin = null;
            this.m_Button6.Left = 390;
            this.m_Button6.Name = "m_Button6";
            this.m_Button6.RequiresTransparency = true;
            this.m_Button6.ScreenOwnerName = "測試";
            this.m_Button6.SymbolIntervalMapper = symbolintervalmapper5;
            this.m_Button6.TextHeight = 48;
            this.m_Button6.TextValue = 0D;
            this.m_Button6.TextWidth = 182;
            this.m_Button6.Top = 176;
            this.m_Button6.Value = 0D;
            this.m_Button6.VisibleDynamicsValue = true;
            this.m_Button6.VisualPropertiesHashCode = -1757690157;
            this.m_Button6.Width = 192;
            // 
            // m_Button7
            // 
            this.m_Button7.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button7.BlinkDynamicsValue = false;
            this.m_Button7.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button7.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button7.EnabledDynamicsValue = true;
            this.m_Button7.FontFamily = "新細明體";
            this.m_Button7.FontSizePixels = 40;
            this.m_Button7.ForceTransparency = true;
            this.m_Button7.Height = 100;
            this.m_Button7.IndicatorMargin = null;
            this.m_Button7.Left = 2;
            this.m_Button7.Name = "m_Button7";
            this.m_Button7.RequiresTransparency = true;
            this.m_Button7.ScreenOwnerName = "測試";
            this.m_Button7.SymbolIntervalMapper = symbolintervalmapper6;
            this.m_Button7.TextHeight = 48;
            this.m_Button7.TextValue = 0D;
            this.m_Button7.TextWidth = 182;
            this.m_Button7.Top = 379;
            this.m_Button7.Value = 0D;
            this.m_Button7.VisibleDynamicsValue = true;
            this.m_Button7.VisualPropertiesHashCode = -1757690157;
            this.m_Button7.Width = 192;
            // 
            // m_Button9
            // 
            this.m_Button9.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button9.BlinkDynamicsValue = false;
            this.m_Button9.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button9.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button9.EnabledDynamicsValue = true;
            this.m_Button9.FontFamily = "新細明體";
            this.m_Button9.FontSizePixels = 40;
            this.m_Button9.ForceTransparency = true;
            this.m_Button9.Height = 100;
            this.m_Button9.IndicatorMargin = null;
            this.m_Button9.Left = 390;
            this.m_Button9.Name = "m_Button9";
            this.m_Button9.RequiresTransparency = true;
            this.m_Button9.ScreenOwnerName = "測試";
            this.m_Button9.SymbolIntervalMapper = symbolintervalmapper7;
            this.m_Button9.TextHeight = 48;
            this.m_Button9.TextValue = 0D;
            this.m_Button9.TextWidth = 182;
            this.m_Button9.Top = 75;
            this.m_Button9.Value = 0D;
            this.m_Button9.VisibleDynamicsValue = true;
            this.m_Button9.VisualPropertiesHashCode = -1757690157;
            this.m_Button9.Width = 192;
            // 
            // m_Button10
            // 
            this.m_Button10.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button10.BlinkDynamicsValue = false;
            this.m_Button10.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button10.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button10.EnabledDynamicsValue = true;
            this.m_Button10.FontFamily = "新細明體";
            this.m_Button10.FontSizePixels = 40;
            this.m_Button10.ForceTransparency = true;
            this.m_Button10.Height = 100;
            this.m_Button10.IndicatorMargin = null;
            this.m_Button10.Left = 2;
            this.m_Button10.Name = "m_Button10";
            this.m_Button10.RequiresTransparency = true;
            this.m_Button10.ScreenOwnerName = "測試";
            this.m_Button10.SymbolIntervalMapper = symbolintervalmapper8;
            this.m_Button10.TextHeight = 48;
            this.m_Button10.TextValue = 0D;
            this.m_Button10.TextWidth = 182;
            this.m_Button10.Top = 277;
            this.m_Button10.Value = 0D;
            this.m_Button10.VisibleDynamicsValue = true;
            this.m_Button10.VisualPropertiesHashCode = -1757690157;
            this.m_Button10.Width = 192;
            // 
            // m_Button11
            // 
            this.m_Button11.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button11.BlinkDynamicsValue = false;
            this.m_Button11.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button11.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button11.EnabledDynamicsValue = true;
            this.m_Button11.FontFamily = "新細明體";
            this.m_Button11.FontSizePixels = 40;
            this.m_Button11.ForceTransparency = true;
            this.m_Button11.Height = 100;
            this.m_Button11.IndicatorMargin = null;
            this.m_Button11.Left = 390;
            this.m_Button11.Name = "m_Button11";
            this.m_Button11.RequiresTransparency = true;
            this.m_Button11.ScreenOwnerName = "測試";
            this.m_Button11.SymbolIntervalMapper = symbolintervalmapper9;
            this.m_Button11.TextHeight = 48;
            this.m_Button11.TextValue = 0D;
            this.m_Button11.TextWidth = 182;
            this.m_Button11.Top = 379;
            this.m_Button11.Value = 0D;
            this.m_Button11.VisibleDynamicsValue = true;
            this.m_Button11.VisualPropertiesHashCode = -1757690157;
            this.m_Button11.Width = 192;
            // 
            // m_Button12
            // 
            this.m_Button12.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button12.BlinkDynamicsValue = false;
            this.m_Button12.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button12.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button12.EnabledDynamicsValue = true;
            this.m_Button12.FontFamily = "新細明體";
            this.m_Button12.FontSizePixels = 40;
            this.m_Button12.ForceTransparency = true;
            this.m_Button12.Height = 100;
            this.m_Button12.IndicatorMargin = null;
            this.m_Button12.Left = 2;
            this.m_Button12.Name = "m_Button12";
            this.m_Button12.RequiresTransparency = true;
            this.m_Button12.ScreenOwnerName = "測試";
            this.m_Button12.SymbolIntervalMapper = symbolintervalmapper10;
            this.m_Button12.TextHeight = 48;
            this.m_Button12.TextValue = 0D;
            this.m_Button12.TextWidth = 182;
            this.m_Button12.Top = 176;
            this.m_Button12.Value = 0D;
            this.m_Button12.VisibleDynamicsValue = true;
            this.m_Button12.VisualPropertiesHashCode = -1757690157;
            this.m_Button12.Width = 192;
            // 
            // m_Button13
            // 
            this.m_Button13.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button13.BlinkDynamicsValue = false;
            this.m_Button13.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button13.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button13.EnabledDynamicsValue = true;
            this.m_Button13.FontFamily = "新細明體";
            this.m_Button13.FontSizePixels = 40;
            this.m_Button13.ForceTransparency = true;
            this.m_Button13.Height = 100;
            this.m_Button13.IndicatorMargin = null;
            this.m_Button13.Left = 196;
            this.m_Button13.Name = "m_Button13";
            this.m_Button13.RequiresTransparency = true;
            this.m_Button13.ScreenOwnerName = "測試";
            this.m_Button13.SymbolIntervalMapper = symbolintervalmapper11;
            this.m_Button13.TextHeight = 48;
            this.m_Button13.TextValue = 0D;
            this.m_Button13.TextWidth = 182;
            this.m_Button13.Top = 277;
            this.m_Button13.Value = 0D;
            this.m_Button13.VisibleDynamicsValue = true;
            this.m_Button13.VisualPropertiesHashCode = -1757690157;
            this.m_Button13.Width = 192;
            // 
            // m_Button8
            // 
            this.m_Button8.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button8.BlinkDynamicsValue = false;
            this.m_Button8.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button8.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button8.EnabledDynamicsValue = true;
            this.m_Button8.FontFamily = "新細明體";
            this.m_Button8.FontSizePixels = 30;
            this.m_Button8.ForceTransparency = true;
            this.m_Button8.Height = 94;
            this.m_Button8.IndicatorMargin = null;
            this.m_Button8.Left = 0;
            this.m_Button8.MultiLine = true;
            this.m_Button8.Name = "m_Button8";
            this.m_Button8.RequiresTransparency = true;
            this.m_Button8.ScreenOwnerName = "測試";
            this.m_Button8.SymbolIntervalMapper = symbolintervalmapper12;
            this.m_Button8.TextHeight = 72;
            this.m_Button8.TextValue = 0D;
            this.m_Button8.TextWidth = 146;
            this.m_Button8.Top = 194;
            this.m_Button8.Value = 0D;
            this.m_Button8.VisibleDynamicsValue = true;
            this.m_Button8.VisualPropertiesHashCode = -283891687;
            this.m_Button8.Width = 156;
            // 
            // m_Button14
            // 
            this.m_Button14.BlinkDynamicsValue = false;
            this.m_Button14.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button14.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            brushdynamicsconvertercf1.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval1.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(215))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval2.End = 1D;
            brushcfinterval2.Start = 1D;
            brushcfinterval2.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(178)))), ((int)(((byte)(207))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval1);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval2);
            this.m_Button14.EnabledDynamicsValue = true;
            this.m_Button14.FontFamily = "新細明體";
            this.m_Button14.FontSizePixels = 35;
            this.m_Button14.ForceTransparency = true;
            this.m_Button14.Height = 94;
            this.m_Button14.IndicatorMargin = null;
            this.m_Button14.Left = 0;
            this.m_Button14.MultiLine = true;
            this.m_Button14.Name = "m_Button14";
            this.m_Button14.RequiresTransparency = true;
            this.m_Button14.ScreenOwnerName = "測試";
            this.m_Button14.SymbolIntervalMapper = symbolintervalmapper13;
            this.m_Button14.TextHeight = 84;
            stringintervalmappercf1.DefaultValue = "Step\r\nStatus";
            stringintervalcf1.Value = "Step\r\nStatus";
            stringintervalcf2.End = 1D;
            stringintervalcf2.Start = 1D;
            stringintervalcf2.Value = "Cycle\r\nStatus";
            stringintervalmappercf1.Intervals.Add(stringintervalcf1);
            stringintervalmappercf1.Intervals.Add(stringintervalcf2);
            this.m_Button14.TextIntervalMapper = stringintervalmappercf1;
            this.m_Button14.TextValue = 0D;
            this.m_Button14.TextWidth = 146;
            this.m_Button14.Top = 97;
            this.m_Button14.Value = 0D;
            this.m_Button14.VisibleDynamicsValue = true;
            this.m_Button14.VisualPropertiesHashCode = -283891687;
            this.m_Button14.Width = 156;
            // 
            // m_Button15
            // 
            this.m_Button15.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button15.BlinkDynamicsValue = false;
            this.m_Button15.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button15.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button15.EnabledDynamicsValue = true;
            this.m_Button15.FontFamily = "新細明體";
            this.m_Button15.FontSizePixels = 40;
            this.m_Button15.ForceTransparency = true;
            this.m_Button15.Height = 94;
            this.m_Button15.IndicatorMargin = null;
            this.m_Button15.Left = 0;
            this.m_Button15.MultiLine = true;
            this.m_Button15.Name = "m_Button15";
            this.m_Button15.RequiresTransparency = true;
            this.m_Button15.ScreenOwnerName = "測試";
            this.m_Button15.SymbolIntervalMapper = symbolintervalmapper14;
            this.m_Button15.TextHeight = 48;
            this.m_Button15.TextValue = 0D;
            this.m_Button15.TextWidth = 146;
            this.m_Button15.Top = 0;
            this.m_Button15.Value = 0D;
            this.m_Button15.VisibleDynamicsValue = true;
            this.m_Button15.VisualPropertiesHashCode = -283891687;
            this.m_Button15.Width = 156;
            // 
            // m_Group
            // 
            this.m_Group.BlinkDynamicsValue = false;
            this.m_Group.Components.Add(this.m_Button8);
            this.m_Group.Components.Add(this.m_Button14);
            this.m_Group.Components.Add(this.m_Button15);
            this.m_Group.EnabledDynamicsValue = true;
            this.m_Group.Height = 286;
            this.m_Group.Left = 638;
            this.m_Group.Name = "m_Group";
            this.m_Group.ParentGroup = null;
            this.m_Group.ScreenOwnerName = "測試";
            this.m_Group.Top = 73;
            this.m_Group.VisibleDynamicsValue = true;
            this.m_Group.Width = 156;
            // 
            // m_bPG_Main
            // 
            this.m_bPG_Main.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_bPG_Main.BlinkDynamicsValue = false;
            this.m_bPG_Main.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(216)))), ((int)(((byte)(230))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_bPG_Main.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_bPG_Main.EnabledDynamicsValue = true;
            this.m_bPG_Main.FontFamily = "新細明體";
            this.m_bPG_Main.FontSizePixels = 40;
            this.m_bPG_Main.ForceTransparency = true;
            this.m_bPG_Main.Height = 66;
            this.m_bPG_Main.IndicatorMargin = null;
            this.m_bPG_Main.Left = 1;
            this.m_bPG_Main.Name = "m_bPG_Main";
            this.m_bPG_Main.RequiresTransparency = true;
            this.m_bPG_Main.ScreenOwnerName = "測試";
            this.m_bPG_Main.SymbolIntervalMapper = symbolintervalmapper15;
            this.m_bPG_Main.TextHeight = 48;
            this.m_bPG_Main.TextValue = 0D;
            this.m_bPG_Main.TextWidth = 90;
            this.m_bPG_Main.Top = 0;
            this.m_bPG_Main.Value = 0D;
            this.m_bPG_Main.VisibleDynamicsValue = true;
            this.m_bPG_Main.VisualPropertiesHashCode = -1250412459;
            this.m_bPG_Main.Width = 100;
            // 
            // m_Button
            // 
            this.m_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontFamily = "新細明體";
            this.m_Button.FontSizePixels = 40;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Height = 66;
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Left = 106;
            this.m_Button.MultiLine = true;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "測試";
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper16;
            this.m_Button.TextHeight = 48;
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 90;
            this.m_Button.Top = 0;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = -62276343;
            this.m_Button.Width = 100;
            // 
            // m_Button1
            // 
            this.m_Button1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(216)))), ((int)(((byte)(230))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BlinkDynamicsValue = false;
            this.m_Button1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(216)))), ((int)(((byte)(230))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button1.EnabledDynamicsValue = true;
            this.m_Button1.FontFamily = "新細明體";
            this.m_Button1.FontSizePixels = 40;
            this.m_Button1.ForceTransparency = true;
            this.m_Button1.Height = 66;
            this.m_Button1.IndicatorMargin = null;
            this.m_Button1.Left = 211;
            this.m_Button1.Name = "m_Button1";
            this.m_Button1.RequiresTransparency = true;
            this.m_Button1.ScreenOwnerName = "測試";
            this.m_Button1.SymbolIntervalMapper = symbolintervalmapper17;
            this.m_Button1.TextHeight = 48;
            this.m_Button1.TextValue = 0D;
            this.m_Button1.TextWidth = 90;
            this.m_Button1.Top = 0;
            this.m_Button1.Value = 0D;
            this.m_Button1.VisibleDynamicsValue = true;
            this.m_Button1.VisualPropertiesHashCode = -200374946;
            this.m_Button1.Width = 100;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "測試";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_測試 = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_測試) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Line);
            this.DrawingPrimitives.Add(this.m_Button2);
            this.DrawingPrimitives.Add(this.m_Button3);
            this.DrawingPrimitives.Add(this.m_Button4);
            this.DrawingPrimitives.Add(this.m_Button5);
            this.DrawingPrimitives.Add(this.m_Button6);
            this.DrawingPrimitives.Add(this.m_Button7);
            this.DrawingPrimitives.Add(this.m_Button9);
            this.DrawingPrimitives.Add(this.m_Button10);
            this.DrawingPrimitives.Add(this.m_Button11);
            this.DrawingPrimitives.Add(this.m_Button12);
            this.DrawingPrimitives.Add(this.m_Button13);
            this.DrawingPrimitives.Add(this.m_Button8);
            this.DrawingPrimitives.Add(this.m_Button14);
            this.DrawingPrimitives.Add(this.m_Button15);
            this.DrawingPrimitives.Add(this.m_Group);
            this.DrawingPrimitives.Add(this.m_bPG_Main);
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_Button1);
            ((System.ComponentModel.ISupportInitialize)(this.m_Button2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button9)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button10)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button11)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button12)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button13)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button14)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button15)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_bPG_Main)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).EndInit();
        }
        
        private void m_Button2_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button2", "MouseDown", "Set Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB.SetTag();
        }
        
        private void m_Button2_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button2", "MouseUp", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB.ResetTag();
        }
        
        private void m_Button2_Action_MouseLeave(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button2", "MouseLeave", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB.ResetTag();
        }
        
        private void m_Button3_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button3", "MouseDown", "Set Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S5.SetTag();
        }
        
        private void m_Button3_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button3", "MouseUp", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S5.ResetTag();
        }
        
        private void m_Button3_Action_MouseLeave(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button3", "MouseLeave", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S5.ResetTag();
        }
        
        private void m_Button4_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button4", "MouseDown", "Set Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S9.SetTag();
        }
        
        private void m_Button4_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button4", "MouseUp", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S9.ResetTag();
        }
        
        private void m_Button4_Action_MouseLeave(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button4", "MouseLeave", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S9.ResetTag();
        }
        
        private void m_Button5_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button5", "MouseDown", "Set Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S2.SetTag();
        }
        
        private void m_Button5_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button5", "MouseUp", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S2.ResetTag();
        }
        
        private void m_Button5_Action_MouseLeave(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button5", "MouseLeave", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S2.ResetTag();
        }
        
        private void m_Button6_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button6", "MouseDown", "Set Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S6.SetTag();
        }
        
        private void m_Button6_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button6", "MouseUp", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S6.ResetTag();
        }
        
        private void m_Button6_Action_MouseLeave(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button6", "MouseLeave", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S6.ResetTag();
        }
        
        private void m_Button7_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button7", "MouseDown", "Set Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S10.SetTag();
        }
        
        private void m_Button7_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button7", "MouseUp", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S10.ResetTag();
        }
        
        private void m_Button7_Action_MouseLeave(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button7", "MouseLeave", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S10.ResetTag();
        }
        
        private void m_Button9_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button9", "MouseDown", "Set Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S3.SetTag();
        }
        
        private void m_Button9_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button9", "MouseUp", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S3.ResetTag();
        }
        
        private void m_Button9_Action_MouseLeave(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button9", "MouseLeave", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S3.ResetTag();
        }
        
        private void m_Button10_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button10", "MouseDown", "Set Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S7.SetTag();
        }
        
        private void m_Button10_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button10", "MouseUp", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S7.ResetTag();
        }
        
        private void m_Button10_Action_MouseLeave(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button10", "MouseLeave", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S7.ResetTag();
        }
        
        private void m_Button11_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button11", "MouseDown", "Set Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S11.SetTag();
        }
        
        private void m_Button11_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button11", "MouseUp", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S11.ResetTag();
        }
        
        private void m_Button11_Action_MouseLeave(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button11", "MouseLeave", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S11.ResetTag();
        }
        
        private void m_Button12_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button12", "MouseDown", "Set Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S4.SetTag();
        }
        
        private void m_Button12_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button12", "MouseUp", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S4.ResetTag();
        }
        
        private void m_Button12_Action_MouseLeave(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button12", "MouseLeave", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S4.ResetTag();
        }
        
        private void m_Button13_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button13", "MouseDown", "Set Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S8.SetTag();
        }
        
        private void m_Button13_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button13", "MouseUp", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S8.ResetTag();
        }
        
        private void m_Button13_Action_MouseLeave(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button13", "MouseLeave", "Reset Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.TestPB_S8.ResetTag();
        }
        
        private void m_Button8_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button8", "MouseDown", "Set Tag", "Tags.Index_PB", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Index_PB.SetTag();
        }
        
        private void m_Button8_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button8", "MouseUp", "Reset Tag", "Tags.Index_PB", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Index_PB.ResetTag();
        }
        
        private void m_Button8_Action_MouseLeave(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button8", "MouseLeave", "Reset Tag", "Tags.Index_PB", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.Index_PB.ResetTag();
        }
        
        private void m_Button14_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button14", "Click", "Toggle Tag", "", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.StepStatus.ToggleTag();
        }
        
        private void m_Button15_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button15", "Click", "Show IP Settings", "", "");
            Core.Api.Service.ServiceContainerCF.GetService<Neo.ApplicationFramework.Interfaces.INetworkService>().ShowIpSettings();
        }
        
        private void m_bPG_Main_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bPG_Main", "Click", "Show Screen", "主頁", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.主頁.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bPG_Main", "Click", "Set Tag", "Tags.AutoStatus", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.AutoStatus.SetTag();
        }
        
        private void m_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Show Screen", "手動選擇", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.手動選擇.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Reset Tag", "Tags.AutoStatus", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.AutoStatus.ResetTag();
        }
        
        private void m_Button1_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button1", "Click", "Show Screen", "測試", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.測試.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button1", "Click", "Set Tag", "Tags.AutoStatus", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.AutoStatus.SetTag();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(測試));
            this.m_Button2.Text = resources.GetText("測試.Button2.Text", "TEST1");
            this.m_Button8.Text = resources.GetText("測試.Button8.Text", "轉盤\r\n啟動");
            this.m_Button3.Text = resources.GetText("測試.Button3.Text", "TEST5");
            this.m_Button4.Text = resources.GetText("測試.Button4.Text", "TEST9");
            this.m_Button5.Text = resources.GetText("測試.Button5.Text", "TEST2");
            this.m_Button6.Text = resources.GetText("測試.Button6.Text", "TEST6");
            this.m_Button7.Text = resources.GetText("測試.Button7.Text", "TEST10");
            this.m_Button9.Text = resources.GetText("測試.Button9.Text", "TEST3");
            this.m_Button10.Text = resources.GetText("測試.Button10.Text", "TEST7");
            this.m_Button11.Text = resources.GetText("測試.Button11.Text", "TEST11");
            this.m_Button12.Text = resources.GetText("測試.Button12.Text", "TEST4");
            this.m_Button13.Text = resources.GetText("測試.Button13.Text", "TEST8");
            this.m_Button14.Text = resources.GetText("測試.Button14.Text", "Step\r\nStatus");
            this.m_Button15.Text = resources.GetText("測試.Button15.Text", "IP");
            this.m_bPG_Main.Text = resources.GetText("測試.bPG_Main.Text", "主頁");
            this.m_Button.Text = resources.GetText("測試.Button.Text", "手動");
            this.m_Button1.Text = resources.GetText("測試.Button1.Text", "測試");
            resources.ApplyTexts(this.m_Button14, "Texts", "測試.Button14.Texts[0]", "Step\r\nStatus", "測試.Button14.Texts[1]", "Cycle\r\nStatus");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_測試) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.TestPB_S8"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button13.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.TestPB_S4"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button12.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.TestPB_S11"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button11.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.Index_PB"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button8.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Background", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.StepStatus"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf1);
            this.m_Button14.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("TextValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.StepStatus"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button14.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding7 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.StepStatus"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button14.DataBindings.Add(dynamicBinding7);
            this.m_DynamicBindings.Add(dynamicBinding7);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding8 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.TestPB_S7"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button10.DataBindings.Add(dynamicBinding8);
            this.m_DynamicBindings.Add(dynamicBinding8);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding9 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.TestPB_S9"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button4.DataBindings.Add(dynamicBinding9);
            this.m_DynamicBindings.Add(dynamicBinding9);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding10 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.TestPB_S5"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button3.DataBindings.Add(dynamicBinding10);
            this.m_DynamicBindings.Add(dynamicBinding10);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding11 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.TestPB"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button2.DataBindings.Add(dynamicBinding11);
            this.m_DynamicBindings.Add(dynamicBinding11);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding12 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.TestPB_S2"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button5.DataBindings.Add(dynamicBinding12);
            this.m_DynamicBindings.Add(dynamicBinding12);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding13 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.TestPB_S3"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button9.DataBindings.Add(dynamicBinding13);
            this.m_DynamicBindings.Add(dynamicBinding13);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding14 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.TestPB_S10"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button7.DataBindings.Add(dynamicBinding14);
            this.m_DynamicBindings.Add(dynamicBinding14);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding15 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.TestPB_S6"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Button6.DataBindings.Add(dynamicBinding15);
            this.m_DynamicBindings.Add(dynamicBinding15);
        }
    }
}
