//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	public partial class Controller2 : Neo.ApplicationFramework.Tools.OpcClient.DataSourceContainer
	{
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem1;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem2;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem3;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem4;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem5;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem6;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem7;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem8;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem9;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem10;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem11;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem12;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem13;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem15;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem16;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem17;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem18;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem14;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem19;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem20;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem21;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem22;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem23;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem24;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem25;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem26;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem27;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem28;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem29;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem30;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem31;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem32;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem33;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem34;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem35;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem36;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem37;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem38;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem39;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem40;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem41;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem42;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem43;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem44;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem45;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem46;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem47;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem48;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem49;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem50;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem51;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem52;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem53;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem54;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem55;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem56;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem57;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem58;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem59;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem60;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem61;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem62;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem63;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem65;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem66;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem67;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem68;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem69;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem71;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem72;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem73;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem74;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem75;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem76;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem77;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem78;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem79;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem80;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem81;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem82;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem83;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem84;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem85;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem86;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem87;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem88;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem89;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem90;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem91;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem92;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem93;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem94;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem95;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem96;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem97;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem98;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem99;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem100;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem101;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem102;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem103;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem104;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem105;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem106;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem107;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem108;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem64;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem70;
		
		public Controller2()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public override void ConnectDataBindings()
		{
			base.ConnectDataBindings();
		}
		
		private void InitializeObjectCreations()
		{
			this.DataItem1 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem1", "%MX35.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem2 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem2", "%MX35.1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem3 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem3", "%MX35.2", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem4 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem4", "%MX30.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem5 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem5", "%QX5.5", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem6 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem6", "%QX5.6", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem7 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem7", "%QX5.4", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem8 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem8", "%QX1.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem9 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem9", "%MX36.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem10 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem10", "%MX36.1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem11 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem11", "%MX36.2", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem12 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem12", "%MX36.3", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem13 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem13", "%MX36.4", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem15 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem15", "%MX36.6", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem16 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem16", "%MX36.7", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem17 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem17", "%MX37.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem18 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem18", "%MX37.1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem14 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem14", "%MX37.2", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem19 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem19", "%MX36.5", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem20 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem20", "%MX37.3", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem21 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem21", "%QX7.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem22 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem22", "%QX28.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem23 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem23", "%QX6.2", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem24 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem24", "%QX20.3", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem25 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem25", "%QX6.1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem26 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem26", "%QX6.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem27 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem27", "%QX7.1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem28 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem28", "%QX8.2", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem29 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem29", "%QX5.7", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem30 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem30", "%IX31.3", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem31 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem31", "%IX32.3", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem32 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem32", "%IX31.1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem33 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem33", "%MX38.2", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem34 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem34", "%MX38.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem35 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem35", "%MX38.1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem36 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem36", "%MX38.3", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem37 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem37", "%MX38.4", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem38 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem38", "%QX7.3", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem39 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem39", "%QX7.4", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem40 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem40", "%QX7.6", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem41 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem41", "%QX7.7", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem42 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem42", "%QX8.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem43 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem43", "%MX39.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem44 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem44", "%MX39.1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem45 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem45", "%MX39.2", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem46 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem46", "%MX39.3", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem47 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem47", "%MX39.4", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem48 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem48", "%MX39.5", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem49 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem49", "%MX39.6", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem50 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem50", "%MX47.2", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem51 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem51", "%MX47.3", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem52 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem52", "%MX48.1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem53 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem53", "%QX8.1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem54 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem54", "%QX8.2", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem55 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem55", "%QX8.4", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem56 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem56", "%QX8.7", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem57 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem57", "%QX15.2", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem58 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem58", "%QX15.3", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem59 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem59", "%QX16.1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem60 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem60", "%IX35.1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem61 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem61", "%MX34.5", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem62 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem62", "%MX34.2", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem63 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem63", "%MX34.4", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem65 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem65", "%MX34.3", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem66 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem66", "%MX34.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem67 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem67", "%QX4.6", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem68 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem68", "%QX5.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem69 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem69", "%QX5.2", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem71 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem71", "%IX29.3", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem72 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem72", "%IX29.5", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem73 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem73", "%IX28.5", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem74 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem74", "%IX28.6", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem75 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem75", "%IX64.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem76 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem76", "%QX3.4", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem77 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem77", "%QX3.7", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem78 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem78", "%QX4.2", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem79 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem79", "%QX3.5", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem80 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem80", "%QX4.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem81 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem81", "%QX4.3", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem82 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem82", "%QX4.5", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem83 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem83", "%QX15.1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem84 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem84", "%QX15.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem85 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem85", "%QX16.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem86 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem86", "%MX32.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem87 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem87", "%MX32.3", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem88 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem88", "%MX32.6", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem89 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem89", "%MX32.1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem90 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem90", "%MX32.4", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem91 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem91", "%MX32.7", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem92 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem92", "%MX32.2", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem93 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem93", "%MX32.5", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem94 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem94", "%MX33.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem95 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem95", "%MX33.1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem96 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem96", "%MX47.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem97 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem97", "%MX47.1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem98 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem98", "%MX48.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem99 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem99", "%IX28.2", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem100 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem100", "%IX27.6", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem101 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem101", "%IX27.2", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem102 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem102", "%MX37.6", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem103 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem103", "%MX37.5", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem104 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem104", "%QX36.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem105 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem105", "%QX36.1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem106 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem106", "%IX34.5", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem107 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem107", "%MX38.5", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem108 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem108", "%QX40.0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem64 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem64", "%MX34.1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem70 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem70", "%IX29.1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem2)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem3)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem4)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem5)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem6)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem7)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem8)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem9)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem10)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem11)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem12)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem13)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem15)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem16)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem17)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem18)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem14)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem19)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem20)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem21)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem22)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem23)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem24)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem25)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem26)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem27)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem28)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem29)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem30)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem31)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem32)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem33)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem34)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem35)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem36)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem37)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem38)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem39)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem40)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem41)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem42)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem43)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem44)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem45)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem46)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem47)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem48)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem49)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem50)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem51)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem52)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem53)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem54)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem55)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem56)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem57)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem58)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem59)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem60)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem61)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem62)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem63)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem65)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem66)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem67)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem68)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem69)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem71)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem72)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem73)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem74)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem75)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem76)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem77)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem78)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem79)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem80)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem81)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem82)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem83)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem84)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem85)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem86)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem87)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem88)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem89)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem90)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem91)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem92)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem93)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem94)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem95)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem96)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem97)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem98)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem99)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem100)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem101)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem102)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem103)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem104)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem105)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem106)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem107)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem108)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem64)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem70)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this.DataItem1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem2)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem3)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem4)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem5)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem6)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem7)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem8)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem9)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem10)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem11)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem12)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem13)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem15)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem16)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem17)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem18)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem14)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem19)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem20)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem21)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem22)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem23)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem24)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem25)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem26)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem27)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem28)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem29)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem30)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem31)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem32)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem33)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem34)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem35)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem36)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem37)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem38)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem39)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem40)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem41)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem42)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem43)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem44)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem45)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem46)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem47)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem48)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem49)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem50)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem51)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem52)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem53)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem54)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem55)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem56)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem57)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem58)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem59)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem60)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem61)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem62)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem63)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem65)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem66)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem67)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem68)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem69)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem71)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem72)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem73)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem74)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem75)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem76)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem77)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem78)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem79)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem80)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem81)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem82)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem83)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem84)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem85)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem86)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem87)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem88)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem89)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem90)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem91)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem92)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem93)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem94)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem95)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem96)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem97)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem98)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem99)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem100)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem101)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem102)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem103)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem104)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem105)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem106)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem107)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem108)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem64)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem70)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.DataItems.Add(this.DataItem1);
			this.DataItems.Add(this.DataItem2);
			this.DataItems.Add(this.DataItem3);
			this.DataItems.Add(this.DataItem4);
			this.DataItems.Add(this.DataItem5);
			this.DataItems.Add(this.DataItem6);
			this.DataItems.Add(this.DataItem7);
			this.DataItems.Add(this.DataItem8);
			this.DataItems.Add(this.DataItem9);
			this.DataItems.Add(this.DataItem10);
			this.DataItems.Add(this.DataItem11);
			this.DataItems.Add(this.DataItem12);
			this.DataItems.Add(this.DataItem13);
			this.DataItems.Add(this.DataItem15);
			this.DataItems.Add(this.DataItem16);
			this.DataItems.Add(this.DataItem17);
			this.DataItems.Add(this.DataItem18);
			this.DataItems.Add(this.DataItem14);
			this.DataItems.Add(this.DataItem19);
			this.DataItems.Add(this.DataItem20);
			this.DataItems.Add(this.DataItem21);
			this.DataItems.Add(this.DataItem22);
			this.DataItems.Add(this.DataItem23);
			this.DataItems.Add(this.DataItem24);
			this.DataItems.Add(this.DataItem25);
			this.DataItems.Add(this.DataItem26);
			this.DataItems.Add(this.DataItem27);
			this.DataItems.Add(this.DataItem28);
			this.DataItems.Add(this.DataItem29);
			this.DataItems.Add(this.DataItem30);
			this.DataItems.Add(this.DataItem31);
			this.DataItems.Add(this.DataItem32);
			this.DataItems.Add(this.DataItem33);
			this.DataItems.Add(this.DataItem34);
			this.DataItems.Add(this.DataItem35);
			this.DataItems.Add(this.DataItem36);
			this.DataItems.Add(this.DataItem37);
			this.DataItems.Add(this.DataItem38);
			this.DataItems.Add(this.DataItem39);
			this.DataItems.Add(this.DataItem40);
			this.DataItems.Add(this.DataItem41);
			this.DataItems.Add(this.DataItem42);
			this.DataItems.Add(this.DataItem43);
			this.DataItems.Add(this.DataItem44);
			this.DataItems.Add(this.DataItem45);
			this.DataItems.Add(this.DataItem46);
			this.DataItems.Add(this.DataItem47);
			this.DataItems.Add(this.DataItem48);
			this.DataItems.Add(this.DataItem49);
			this.DataItems.Add(this.DataItem50);
			this.DataItems.Add(this.DataItem51);
			this.DataItems.Add(this.DataItem52);
			this.DataItems.Add(this.DataItem53);
			this.DataItems.Add(this.DataItem54);
			this.DataItems.Add(this.DataItem55);
			this.DataItems.Add(this.DataItem56);
			this.DataItems.Add(this.DataItem57);
			this.DataItems.Add(this.DataItem58);
			this.DataItems.Add(this.DataItem59);
			this.DataItems.Add(this.DataItem60);
			this.DataItems.Add(this.DataItem61);
			this.DataItems.Add(this.DataItem62);
			this.DataItems.Add(this.DataItem63);
			this.DataItems.Add(this.DataItem65);
			this.DataItems.Add(this.DataItem66);
			this.DataItems.Add(this.DataItem67);
			this.DataItems.Add(this.DataItem68);
			this.DataItems.Add(this.DataItem69);
			this.DataItems.Add(this.DataItem71);
			this.DataItems.Add(this.DataItem72);
			this.DataItems.Add(this.DataItem73);
			this.DataItems.Add(this.DataItem74);
			this.DataItems.Add(this.DataItem75);
			this.DataItems.Add(this.DataItem76);
			this.DataItems.Add(this.DataItem77);
			this.DataItems.Add(this.DataItem78);
			this.DataItems.Add(this.DataItem79);
			this.DataItems.Add(this.DataItem80);
			this.DataItems.Add(this.DataItem81);
			this.DataItems.Add(this.DataItem82);
			this.DataItems.Add(this.DataItem83);
			this.DataItems.Add(this.DataItem84);
			this.DataItems.Add(this.DataItem85);
			this.DataItems.Add(this.DataItem86);
			this.DataItems.Add(this.DataItem87);
			this.DataItems.Add(this.DataItem88);
			this.DataItems.Add(this.DataItem89);
			this.DataItems.Add(this.DataItem90);
			this.DataItems.Add(this.DataItem91);
			this.DataItems.Add(this.DataItem92);
			this.DataItems.Add(this.DataItem93);
			this.DataItems.Add(this.DataItem94);
			this.DataItems.Add(this.DataItem95);
			this.DataItems.Add(this.DataItem96);
			this.DataItems.Add(this.DataItem97);
			this.DataItems.Add(this.DataItem98);
			this.DataItems.Add(this.DataItem99);
			this.DataItems.Add(this.DataItem100);
			this.DataItems.Add(this.DataItem101);
			this.DataItems.Add(this.DataItem102);
			this.DataItems.Add(this.DataItem103);
			this.DataItems.Add(this.DataItem104);
			this.DataItems.Add(this.DataItem105);
			this.DataItems.Add(this.DataItem106);
			this.DataItems.Add(this.DataItem107);
			this.DataItems.Add(this.DataItem108);
			this.DataItems.Add(this.DataItem64);
			this.DataItems.Add(this.DataItem70);
			this.Driver = "Beckhoff_ADS_Pre2.Beckhoff_ADS_Pre2.1";
			this.Node = "";
			this.Servername = "Beijer.InprocessNeo.1";
			this.TargetInfoString = "iXDeveloper;WinCe6;Beijer;Exter iX;X2 base 7;zh-Hant;";
			this.Url = "";
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Controller2));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected override void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
			base.ApplyLanguage();
		}
	}
}
