//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class Z軸位置移動確認頁 : Neo.ApplicationFramework.Controls.Controls.Form {
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_bAct_GoTakeTrayPosPB;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_bAct_GoFixMovePB;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_bPG_Tray;
        
        private bool m_Initialized_Z軸位置移動確認頁;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf1;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf2;
        
        public Z軸位置移動確認頁() {
            this.InitializeComponent();
            this.m_bAct_GoTakeTrayPosPB.MouseDown += new System.EventHandler(this.m_bAct_GoTakeTrayPosPB_Action_PreviewMouseDown);
            this.m_bAct_GoTakeTrayPosPB.MouseUp += new System.EventHandler(this.m_bAct_GoTakeTrayPosPB_Action_PreviewMouseUp);
            this.m_bAct_GoTakeTrayPosPB.MouseLeave += new System.EventHandler(this.m_bAct_GoTakeTrayPosPB_Action_MouseLeave);
            this.m_bAct_GoFixMovePB.MouseDown += new System.EventHandler(this.m_bAct_GoFixMovePB_Action_PreviewMouseDown);
            this.m_bAct_GoFixMovePB.MouseUp += new System.EventHandler(this.m_bAct_GoFixMovePB_Action_PreviewMouseUp);
            this.m_bAct_GoFixMovePB.MouseLeave += new System.EventHandler(this.m_bAct_GoFixMovePB_Action_MouseLeave);
            this.m_bPG_Tray.Click += new System.EventHandler(this.m_bPG_Tray_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter bAct_GoTakeTrayPosPB {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_bAct_GoTakeTrayPosPB);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter bAct_GoFixMovePB {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_bAct_GoFixMovePB);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter bPG_Tray {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_bPG_Tray);
            }
        }
        
        private void InitializeComponent() {
            this.brushdynamicsconvertercf2 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            this.brushdynamicsconvertercf1 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval1 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval2 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval3 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval4 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_bAct_GoTakeTrayPosPB = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_bAct_GoFixMovePB = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_bPG_Tray = new Neo.ApplicationFramework.Controls.Controls.Button();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_bAct_GoTakeTrayPosPB)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_bAct_GoFixMovePB)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_bPG_Tray)).BeginInit();
            this.SuspendLayout();
            // 
            // Z軸位置移動確認頁
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.SingleBorder;
            this.ControlBox = false;
            // 
            // m_Text
            // 
            this.m_Text.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Text.BlinkDynamicsValue = false;
            this.m_Text.EnabledDynamicsValue = true;
            this.m_Text.FontFamily = "新細明體";
            this.m_Text.FontSizePixels = 36;
            this.m_Text.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.m_Text.Height = 74;
            this.m_Text.Left = 183;
            this.m_Text.MultiLine = true;
            this.m_Text.Name = "m_Text";
            this.m_Text.ScreenOwnerName = "Z軸位置移動確認頁";
            this.m_Text.TextHorizontalAlignment = "Center";
            this.m_Text.Top = 24;
            this.m_Text.VisibleDynamicsValue = true;
            this.m_Text.Width = 197;
            // 
            // m_bAct_GoTakeTrayPosPB
            // 
            this.m_bAct_GoTakeTrayPosPB.BlinkDynamicsValue = false;
            this.m_bAct_GoTakeTrayPosPB.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_bAct_GoTakeTrayPosPB.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            brushdynamicsconvertercf1.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.LightBlue, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval1.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(227)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(183)))), ((int)(((byte)(239))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalWithMiddleStop);
            brushcfinterval2.End = 1D;
            brushcfinterval2.Start = 1D;
            brushcfinterval2.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(114)))), ((int)(((byte)(188))))), System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(188)))), ((int)(((byte)(255))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalWithMiddleStop);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval1);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval2);
            this.m_bAct_GoTakeTrayPosPB.EnabledDynamicsValue = true;
            this.m_bAct_GoTakeTrayPosPB.FontFamily = "新細明體";
            this.m_bAct_GoTakeTrayPosPB.FontSizePixels = 18;
            this.m_bAct_GoTakeTrayPosPB.ForceTransparency = true;
            this.m_bAct_GoTakeTrayPosPB.Height = 70;
            this.m_bAct_GoTakeTrayPosPB.IndicatorMargin = null;
            this.m_bAct_GoTakeTrayPosPB.Left = 281;
            this.m_bAct_GoTakeTrayPosPB.MultiLine = true;
            this.m_bAct_GoTakeTrayPosPB.Name = "m_bAct_GoTakeTrayPosPB";
            this.m_bAct_GoTakeTrayPosPB.RequiresTransparency = true;
            this.m_bAct_GoTakeTrayPosPB.ScreenOwnerName = "Z軸位置移動確認頁";
            this.m_bAct_GoTakeTrayPosPB.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_bAct_GoTakeTrayPosPB.SymbolName = "";
            this.m_bAct_GoTakeTrayPosPB.TextHeight = 42;
            this.m_bAct_GoTakeTrayPosPB.TextValue = 0D;
            this.m_bAct_GoTakeTrayPosPB.TextWidth = 90;
            this.m_bAct_GoTakeTrayPosPB.Top = 233;
            this.m_bAct_GoTakeTrayPosPB.Value = 0D;
            this.m_bAct_GoTakeTrayPosPB.VisibleDynamicsValue = true;
            this.m_bAct_GoTakeTrayPosPB.VisualPropertiesHashCode = 1905194160;
            this.m_bAct_GoTakeTrayPosPB.Width = 100;
            // 
            // m_bAct_GoFixMovePB
            // 
            this.m_bAct_GoFixMovePB.BlinkDynamicsValue = false;
            this.m_bAct_GoFixMovePB.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_bAct_GoFixMovePB.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            brushdynamicsconvertercf2.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.LightBlue, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval3.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(227)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(183)))), ((int)(((byte)(239))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalWithMiddleStop);
            brushcfinterval4.End = 1D;
            brushcfinterval4.Start = 1D;
            brushcfinterval4.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(114)))), ((int)(((byte)(188))))), System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(188)))), ((int)(((byte)(255))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalWithMiddleStop);
            brushdynamicsconvertercf2.BrushIntervalMapper.Intervals.Add(brushcfinterval3);
            brushdynamicsconvertercf2.BrushIntervalMapper.Intervals.Add(brushcfinterval4);
            this.m_bAct_GoFixMovePB.EnabledDynamicsValue = true;
            this.m_bAct_GoFixMovePB.FontFamily = "新細明體";
            this.m_bAct_GoFixMovePB.FontSizePixels = 20;
            this.m_bAct_GoFixMovePB.ForceTransparency = true;
            this.m_bAct_GoFixMovePB.Height = 70;
            this.m_bAct_GoFixMovePB.IndicatorMargin = null;
            this.m_bAct_GoFixMovePB.Left = 436;
            this.m_bAct_GoFixMovePB.MultiLine = true;
            this.m_bAct_GoFixMovePB.Name = "m_bAct_GoFixMovePB";
            this.m_bAct_GoFixMovePB.RequiresTransparency = true;
            this.m_bAct_GoFixMovePB.ScreenOwnerName = "Z軸位置移動確認頁";
            this.m_bAct_GoFixMovePB.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_bAct_GoFixMovePB.SymbolName = "";
            this.m_bAct_GoFixMovePB.TextHeight = 48;
            this.m_bAct_GoFixMovePB.TextValue = 0D;
            this.m_bAct_GoFixMovePB.TextWidth = 90;
            this.m_bAct_GoFixMovePB.Top = 233;
            this.m_bAct_GoFixMovePB.Value = 0D;
            this.m_bAct_GoFixMovePB.VisibleDynamicsValue = true;
            this.m_bAct_GoFixMovePB.VisualPropertiesHashCode = 1905194160;
            this.m_bAct_GoFixMovePB.Width = 100;
            // 
            // m_bPG_Tray
            // 
            this.m_bPG_Tray.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_bPG_Tray.BlinkDynamicsValue = false;
            this.m_bPG_Tray.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_bPG_Tray.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_bPG_Tray.EnabledDynamicsValue = true;
            this.m_bPG_Tray.FontFamily = "新細明體";
            this.m_bPG_Tray.FontSizePixels = 20;
            this.m_bPG_Tray.ForceTransparency = true;
            this.m_bPG_Tray.Height = 70;
            this.m_bPG_Tray.IndicatorMargin = null;
            this.m_bPG_Tray.Left = 3;
            this.m_bPG_Tray.MultiLine = true;
            this.m_bPG_Tray.Name = "m_bPG_Tray";
            this.m_bPG_Tray.RequiresTransparency = true;
            this.m_bPG_Tray.ScreenOwnerName = "Z軸位置移動確認頁";
            this.m_bPG_Tray.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_bPG_Tray.TextHeight = 48;
            this.m_bPG_Tray.TextValue = 0D;
            this.m_bPG_Tray.TextWidth = 90;
            this.m_bPG_Tray.Top = 408;
            this.m_bPG_Tray.Value = 0D;
            this.m_bPG_Tray.VisibleDynamicsValue = true;
            this.m_bPG_Tray.VisualPropertiesHashCode = -1049602432;
            this.m_bPG_Tray.Width = 100;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "Z軸位置移動確認頁";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_Z軸位置移動確認頁 = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_Z軸位置移動確認頁) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Text);
            this.DrawingPrimitives.Add(this.m_bAct_GoTakeTrayPosPB);
            this.DrawingPrimitives.Add(this.m_bAct_GoFixMovePB);
            this.DrawingPrimitives.Add(this.m_bPG_Tray);
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_bAct_GoTakeTrayPosPB)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_bAct_GoFixMovePB)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_bPG_Tray)).EndInit();
        }
        
        private void m_bAct_GoTakeTrayPosPB_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bAct_GoTakeTrayPosPB", "MouseDown", "Set Tag", "Tags.HMI_GoTakeTrayPosPB_AxisZ", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.HMI_GoTakeTrayPosPB_AxisZ.SetTag();
        }
        
        private void m_bAct_GoTakeTrayPosPB_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bAct_GoTakeTrayPosPB", "MouseUp", "Reset Tag", "Tags.HMI_GoTakeTrayPosPB_AxisZ", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.HMI_GoTakeTrayPosPB_AxisZ.ResetTag();
        }
        
        private void m_bAct_GoTakeTrayPosPB_Action_MouseLeave(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bAct_GoTakeTrayPosPB", "MouseLeave", "Reset Tag", "Tags.HMI_GoTakeTrayPosPB_AxisZ", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.HMI_GoTakeTrayPosPB_AxisZ.ResetTag();
        }
        
        private void m_bAct_GoFixMovePB_Action_PreviewMouseDown(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bAct_GoFixMovePB", "MouseDown", "Set Tag", "Tags.HMI_GoFixMovePosPB_AxisZ", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.HMI_GoFixMovePosPB_AxisZ.SetTag();
        }
        
        private void m_bAct_GoFixMovePB_Action_PreviewMouseUp(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bAct_GoFixMovePB", "MouseUp", "Reset Tag", "Tags.HMI_GoFixMovePosPB_AxisZ", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.HMI_GoFixMovePosPB_AxisZ.ResetTag();
        }
        
        private void m_bAct_GoFixMovePB_Action_MouseLeave(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bAct_GoFixMovePB", "MouseLeave", "Reset Tag", "Tags.HMI_GoFixMovePosPB_AxisZ", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.HMI_GoFixMovePosPB_AxisZ.ResetTag();
        }
        
        private void m_bPG_Tray_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bPG_Tray", "Click", "Show Screen", "手動_取放盤", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.手動_取放盤.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bPG_Tray", "Click", "Reset Tag", "Tags.AutoStatus", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.AutoStatus.ResetTag();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bPG_Tray", "Click", "Set Tag", "Tags.ManualStatus", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.ManualStatus.SetTag();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Z軸位置移動確認頁));
            this.m_Text.Text = resources.GetText("Z軸位置移動確認頁.Text.Text", "注意!!\r\n此操作可能對機器造成損壞,\r\n請確認目前伺服及料盤狀態,\r\n再行下列操作。");
            this.m_bAct_GoTakeTrayPosPB.Text = resources.GetText("Z軸位置移動確認頁.bAct_GoTakeTrayPosPB.Text", "接料盤位置\r\nGO");
            this.m_bAct_GoFixMovePB.Text = resources.GetText("Z軸位置移動確認頁.bAct_GoFixMovePB.Text", "固定距離\r\nGO");
            this.m_bPG_Tray.Text = resources.GetText("Z軸位置移動確認頁.bPG_Tray.Text", "回取放\r\n料盤");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_Z軸位置移動確認頁) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.HMI_GoFixMovePosPB_AxisZ"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_bAct_GoFixMovePB.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("TextValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.ServoJogForwardPB_AxisZ"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_bAct_GoFixMovePB.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Background", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.HMI_GoFixMovePosPB_AxisZ"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf2);
            this.m_bAct_GoFixMovePB.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.HMI_GoTakeTrayPosPB_AxisZ"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_bAct_GoTakeTrayPosPB.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("TextValue", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.ServoJogForwardPB_AxisZ"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_bAct_GoTakeTrayPosPB.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Background", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.HMI_GoTakeTrayPosPB_AxisZ"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf1);
            this.m_bAct_GoTakeTrayPosPB.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
        }
    }
}
