//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class 手動選擇 : 基礎畫面 {
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button1;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button2;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button3;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button4;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button5;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button6;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button7;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button8;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button9;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button10;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_bPG_Main;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button11;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_Button12;
        
        private bool m_Initialized_手動選擇;
        
        public 手動選擇() {
            this.InitializeComponent();
            this.m_Button.Click += new System.EventHandler(this.m_Button_Action_Click);
            this.m_Button1.Click += new System.EventHandler(this.m_Button1_Action_Click);
            this.m_Button2.Click += new System.EventHandler(this.m_Button2_Action_Click);
            this.m_Button3.Click += new System.EventHandler(this.m_Button3_Action_Click);
            this.m_Button4.Click += new System.EventHandler(this.m_Button4_Action_Click);
            this.m_Button5.Click += new System.EventHandler(this.m_Button5_Action_Click);
            this.m_Button6.Click += new System.EventHandler(this.m_Button6_Action_Click);
            this.m_Button7.Click += new System.EventHandler(this.m_Button7_Action_Click);
            this.m_Button8.Click += new System.EventHandler(this.m_Button8_Action_Click);
            this.m_Button9.Click += new System.EventHandler(this.m_Button9_Action_Click);
            this.m_Button10.Click += new System.EventHandler(this.m_Button10_Action_Click);
            this.m_bPG_Main.Click += new System.EventHandler(this.m_bPG_Main_Action_Click);
            this.m_Button11.Click += new System.EventHandler(this.m_Button11_Action_Click);
            this.m_Button12.Click += new System.EventHandler(this.m_Button12_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button5);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button7 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button7);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button8);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button9 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button9);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button10 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button10);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter bPG_Main {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_bPG_Main);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button11 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button11);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter Button12 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_Button12);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper5 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper6 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper7 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper8 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper9 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper10 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper11 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper12 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper13 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper14 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_Button = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button1 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button2 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button3 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button4 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button5 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button6 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button7 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button8 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button9 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button10 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_bPG_Main = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button11 = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_Button12 = new Neo.ApplicationFramework.Controls.Controls.Button();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button9)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button10)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_bPG_Main)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button11)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button12)).BeginInit();
            this.SuspendLayout();
            // 
            // 手動選擇
            // 
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.ThreeDBorder;
            this.ControlBox = false;
            // 
            // m_Button
            // 
            this.m_Button.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BlinkDynamicsValue = false;
            this.m_Button.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button.EnabledDynamicsValue = true;
            this.m_Button.FontFamily = "新細明體";
            this.m_Button.FontSizePixels = 60;
            this.m_Button.ForceTransparency = true;
            this.m_Button.Height = 132;
            this.m_Button.IndicatorMargin = null;
            this.m_Button.Left = 4;
            this.m_Button.MultiLine = true;
            this.m_Button.Name = "m_Button";
            this.m_Button.RequiresTransparency = true;
            this.m_Button.ScreenOwnerName = "手動選擇";
            this.m_Button.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_Button.TextHeight = 72;
            this.m_Button.TextValue = 0D;
            this.m_Button.TextWidth = 187;
            this.m_Button.Top = 72;
            this.m_Button.Value = 0D;
            this.m_Button.VisibleDynamicsValue = true;
            this.m_Button.VisualPropertiesHashCode = -413671815;
            this.m_Button.Width = 197;
            // 
            // m_Button1
            // 
            this.m_Button1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BlinkDynamicsValue = false;
            this.m_Button1.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button1.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button1.EnabledDynamicsValue = true;
            this.m_Button1.FontFamily = "新細明體";
            this.m_Button1.FontSizePixels = 60;
            this.m_Button1.ForceTransparency = true;
            this.m_Button1.Height = 132;
            this.m_Button1.IndicatorMargin = null;
            this.m_Button1.Left = 4;
            this.m_Button1.MultiLine = true;
            this.m_Button1.Name = "m_Button1";
            this.m_Button1.RequiresTransparency = true;
            this.m_Button1.ScreenOwnerName = "手動選擇";
            this.m_Button1.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_Button1.TextHeight = 72;
            this.m_Button1.TextValue = 0D;
            this.m_Button1.TextWidth = 187;
            this.m_Button1.Top = 205;
            this.m_Button1.Value = 0D;
            this.m_Button1.VisibleDynamicsValue = true;
            this.m_Button1.VisualPropertiesHashCode = -413671815;
            this.m_Button1.Width = 197;
            // 
            // m_Button2
            // 
            this.m_Button2.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button2.BlinkDynamicsValue = false;
            this.m_Button2.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button2.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button2.EnabledDynamicsValue = true;
            this.m_Button2.FontFamily = "新細明體";
            this.m_Button2.FontSizePixels = 60;
            this.m_Button2.ForceTransparency = true;
            this.m_Button2.Height = 132;
            this.m_Button2.IndicatorMargin = null;
            this.m_Button2.Left = 4;
            this.m_Button2.MultiLine = true;
            this.m_Button2.Name = "m_Button2";
            this.m_Button2.RequiresTransparency = true;
            this.m_Button2.ScreenOwnerName = "手動選擇";
            this.m_Button2.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_Button2.TextHeight = 72;
            this.m_Button2.TextValue = 0D;
            this.m_Button2.TextWidth = 187;
            this.m_Button2.Top = 339;
            this.m_Button2.Value = 0D;
            this.m_Button2.VisibleDynamicsValue = true;
            this.m_Button2.VisualPropertiesHashCode = -413671815;
            this.m_Button2.Width = 197;
            // 
            // m_Button3
            // 
            this.m_Button3.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button3.BlinkDynamicsValue = false;
            this.m_Button3.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button3.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button3.EnabledDynamicsValue = true;
            this.m_Button3.FontFamily = "新細明體";
            this.m_Button3.FontSizePixels = 60;
            this.m_Button3.ForceTransparency = true;
            this.m_Button3.Height = 132;
            this.m_Button3.IndicatorMargin = null;
            this.m_Button3.Left = 202;
            this.m_Button3.MultiLine = true;
            this.m_Button3.Name = "m_Button3";
            this.m_Button3.RequiresTransparency = true;
            this.m_Button3.ScreenOwnerName = "手動選擇";
            this.m_Button3.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_Button3.TextHeight = 72;
            this.m_Button3.TextValue = 0D;
            this.m_Button3.TextWidth = 187;
            this.m_Button3.Top = 72;
            this.m_Button3.Value = 0D;
            this.m_Button3.VisibleDynamicsValue = true;
            this.m_Button3.VisualPropertiesHashCode = -413671815;
            this.m_Button3.Width = 197;
            // 
            // m_Button4
            // 
            this.m_Button4.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button4.BlinkDynamicsValue = false;
            this.m_Button4.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button4.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button4.EnabledDynamicsValue = true;
            this.m_Button4.FontFamily = "新細明體";
            this.m_Button4.FontSizePixels = 60;
            this.m_Button4.ForceTransparency = true;
            this.m_Button4.Height = 132;
            this.m_Button4.IndicatorMargin = null;
            this.m_Button4.Left = 202;
            this.m_Button4.MultiLine = true;
            this.m_Button4.Name = "m_Button4";
            this.m_Button4.RequiresTransparency = true;
            this.m_Button4.ScreenOwnerName = "手動選擇";
            this.m_Button4.SymbolIntervalMapper = symbolintervalmapper5;
            this.m_Button4.TextHeight = 72;
            this.m_Button4.TextValue = 0D;
            this.m_Button4.TextWidth = 187;
            this.m_Button4.Top = 205;
            this.m_Button4.Value = 0D;
            this.m_Button4.VisibleDynamicsValue = true;
            this.m_Button4.VisualPropertiesHashCode = -413671815;
            this.m_Button4.Width = 197;
            // 
            // m_Button5
            // 
            this.m_Button5.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button5.BlinkDynamicsValue = false;
            this.m_Button5.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button5.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button5.EnabledDynamicsValue = true;
            this.m_Button5.FontFamily = "新細明體";
            this.m_Button5.FontSizePixels = 60;
            this.m_Button5.ForceTransparency = true;
            this.m_Button5.Height = 132;
            this.m_Button5.IndicatorMargin = null;
            this.m_Button5.Left = 202;
            this.m_Button5.MultiLine = true;
            this.m_Button5.Name = "m_Button5";
            this.m_Button5.RequiresTransparency = true;
            this.m_Button5.ScreenOwnerName = "手動選擇";
            this.m_Button5.SymbolIntervalMapper = symbolintervalmapper6;
            this.m_Button5.TextHeight = 72;
            this.m_Button5.TextValue = 0D;
            this.m_Button5.TextWidth = 187;
            this.m_Button5.Top = 339;
            this.m_Button5.Value = 0D;
            this.m_Button5.VisibleDynamicsValue = true;
            this.m_Button5.VisualPropertiesHashCode = -413671815;
            this.m_Button5.Width = 197;
            // 
            // m_Button6
            // 
            this.m_Button6.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button6.BlinkDynamicsValue = false;
            this.m_Button6.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button6.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button6.EnabledDynamicsValue = true;
            this.m_Button6.FontFamily = "新細明體";
            this.m_Button6.FontSizePixels = 60;
            this.m_Button6.ForceTransparency = true;
            this.m_Button6.Height = 132;
            this.m_Button6.IndicatorMargin = null;
            this.m_Button6.Left = 401;
            this.m_Button6.MultiLine = true;
            this.m_Button6.Name = "m_Button6";
            this.m_Button6.RequiresTransparency = true;
            this.m_Button6.ScreenOwnerName = "手動選擇";
            this.m_Button6.SymbolIntervalMapper = symbolintervalmapper7;
            this.m_Button6.TextHeight = 72;
            this.m_Button6.TextValue = 0D;
            this.m_Button6.TextWidth = 187;
            this.m_Button6.Top = 72;
            this.m_Button6.Value = 0D;
            this.m_Button6.VisibleDynamicsValue = true;
            this.m_Button6.VisualPropertiesHashCode = -413671815;
            this.m_Button6.Width = 197;
            // 
            // m_Button7
            // 
            this.m_Button7.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button7.BlinkDynamicsValue = false;
            this.m_Button7.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button7.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button7.EnabledDynamicsValue = true;
            this.m_Button7.FontFamily = "新細明體";
            this.m_Button7.FontSizePixels = 60;
            this.m_Button7.ForceTransparency = true;
            this.m_Button7.Height = 132;
            this.m_Button7.IndicatorMargin = null;
            this.m_Button7.Left = 401;
            this.m_Button7.MultiLine = true;
            this.m_Button7.Name = "m_Button7";
            this.m_Button7.RequiresTransparency = true;
            this.m_Button7.ScreenOwnerName = "手動選擇";
            this.m_Button7.SymbolIntervalMapper = symbolintervalmapper8;
            this.m_Button7.TextHeight = 72;
            this.m_Button7.TextValue = 0D;
            this.m_Button7.TextWidth = 187;
            this.m_Button7.Top = 205;
            this.m_Button7.Value = 0D;
            this.m_Button7.VisibleDynamicsValue = true;
            this.m_Button7.VisualPropertiesHashCode = -413671815;
            this.m_Button7.Width = 197;
            // 
            // m_Button8
            // 
            this.m_Button8.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button8.BlinkDynamicsValue = false;
            this.m_Button8.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button8.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button8.EnabledDynamicsValue = true;
            this.m_Button8.FontFamily = "新細明體";
            this.m_Button8.FontSizePixels = 60;
            this.m_Button8.ForceTransparency = true;
            this.m_Button8.Height = 132;
            this.m_Button8.IndicatorMargin = null;
            this.m_Button8.Left = 401;
            this.m_Button8.MultiLine = true;
            this.m_Button8.Name = "m_Button8";
            this.m_Button8.RequiresTransparency = true;
            this.m_Button8.ScreenOwnerName = "手動選擇";
            this.m_Button8.SymbolIntervalMapper = symbolintervalmapper9;
            this.m_Button8.TextHeight = 72;
            this.m_Button8.TextValue = 0D;
            this.m_Button8.TextWidth = 187;
            this.m_Button8.Top = 339;
            this.m_Button8.Value = 0D;
            this.m_Button8.VisibleDynamicsValue = true;
            this.m_Button8.VisualPropertiesHashCode = -413671815;
            this.m_Button8.Width = 197;
            // 
            // m_Button9
            // 
            this.m_Button9.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button9.BlinkDynamicsValue = false;
            this.m_Button9.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button9.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button9.EnabledDynamicsValue = true;
            this.m_Button9.FontFamily = "新細明體";
            this.m_Button9.FontSizePixels = 60;
            this.m_Button9.ForceTransparency = true;
            this.m_Button9.Height = 132;
            this.m_Button9.IndicatorMargin = null;
            this.m_Button9.Left = 600;
            this.m_Button9.MultiLine = true;
            this.m_Button9.Name = "m_Button9";
            this.m_Button9.RequiresTransparency = true;
            this.m_Button9.ScreenOwnerName = "手動選擇";
            this.m_Button9.SymbolIntervalMapper = symbolintervalmapper10;
            this.m_Button9.TextHeight = 72;
            this.m_Button9.TextValue = 0D;
            this.m_Button9.TextWidth = 187;
            this.m_Button9.Top = 72;
            this.m_Button9.Value = 0D;
            this.m_Button9.VisibleDynamicsValue = true;
            this.m_Button9.VisualPropertiesHashCode = -413671815;
            this.m_Button9.Width = 197;
            // 
            // m_Button10
            // 
            this.m_Button10.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(200)))), ((int)(((byte)(150))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button10.BlinkDynamicsValue = false;
            this.m_Button10.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button10.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button10.EnabledDynamicsValue = true;
            this.m_Button10.FontFamily = "新細明體";
            this.m_Button10.FontSizePixels = 60;
            this.m_Button10.ForceTransparency = true;
            this.m_Button10.Height = 132;
            this.m_Button10.IndicatorMargin = null;
            this.m_Button10.Left = 600;
            this.m_Button10.MultiLine = true;
            this.m_Button10.Name = "m_Button10";
            this.m_Button10.RequiresTransparency = true;
            this.m_Button10.ScreenOwnerName = "手動選擇";
            this.m_Button10.SymbolIntervalMapper = symbolintervalmapper11;
            this.m_Button10.TextHeight = 72;
            this.m_Button10.TextValue = 0D;
            this.m_Button10.TextWidth = 187;
            this.m_Button10.Top = 205;
            this.m_Button10.Value = 0D;
            this.m_Button10.VisibleDynamicsValue = true;
            this.m_Button10.VisualPropertiesHashCode = -413671815;
            this.m_Button10.Width = 197;
            // 
            // m_bPG_Main
            // 
            this.m_bPG_Main.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_bPG_Main.BlinkDynamicsValue = false;
            this.m_bPG_Main.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(216)))), ((int)(((byte)(230))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_bPG_Main.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_bPG_Main.EnabledDynamicsValue = true;
            this.m_bPG_Main.FontFamily = "新細明體";
            this.m_bPG_Main.FontSizePixels = 40;
            this.m_bPG_Main.ForceTransparency = true;
            this.m_bPG_Main.Height = 66;
            this.m_bPG_Main.IndicatorMargin = null;
            this.m_bPG_Main.Left = 1;
            this.m_bPG_Main.Name = "m_bPG_Main";
            this.m_bPG_Main.RequiresTransparency = true;
            this.m_bPG_Main.ScreenOwnerName = "手動選擇";
            this.m_bPG_Main.SymbolIntervalMapper = symbolintervalmapper12;
            this.m_bPG_Main.TextHeight = 48;
            this.m_bPG_Main.TextValue = 0D;
            this.m_bPG_Main.TextWidth = 90;
            this.m_bPG_Main.Top = 0;
            this.m_bPG_Main.Value = 0D;
            this.m_bPG_Main.VisibleDynamicsValue = true;
            this.m_bPG_Main.VisualPropertiesHashCode = -1250412459;
            this.m_bPG_Main.Width = 100;
            // 
            // m_Button11
            // 
            this.m_Button11.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(216)))), ((int)(((byte)(230))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button11.BlinkDynamicsValue = false;
            this.m_Button11.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(216)))), ((int)(((byte)(230))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button11.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button11.EnabledDynamicsValue = true;
            this.m_Button11.FontFamily = "新細明體";
            this.m_Button11.FontSizePixels = 40;
            this.m_Button11.ForceTransparency = true;
            this.m_Button11.Height = 66;
            this.m_Button11.IndicatorMargin = null;
            this.m_Button11.Left = 106;
            this.m_Button11.MultiLine = true;
            this.m_Button11.Name = "m_Button11";
            this.m_Button11.RequiresTransparency = true;
            this.m_Button11.ScreenOwnerName = "手動選擇";
            this.m_Button11.SymbolIntervalMapper = symbolintervalmapper13;
            this.m_Button11.TextHeight = 48;
            this.m_Button11.TextValue = 0D;
            this.m_Button11.TextWidth = 90;
            this.m_Button11.Top = 0;
            this.m_Button11.Value = 0D;
            this.m_Button11.VisibleDynamicsValue = true;
            this.m_Button11.VisualPropertiesHashCode = -200374946;
            this.m_Button11.Width = 100;
            // 
            // m_Button12
            // 
            this.m_Button12.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button12.BlinkDynamicsValue = false;
            this.m_Button12.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(216)))), ((int)(((byte)(230))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Button12.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_Button12.EnabledDynamicsValue = true;
            this.m_Button12.FontFamily = "新細明體";
            this.m_Button12.FontSizePixels = 40;
            this.m_Button12.ForceTransparency = true;
            this.m_Button12.Height = 66;
            this.m_Button12.IndicatorMargin = null;
            this.m_Button12.Left = 211;
            this.m_Button12.Name = "m_Button12";
            this.m_Button12.RequiresTransparency = true;
            this.m_Button12.ScreenOwnerName = "手動選擇";
            this.m_Button12.SymbolIntervalMapper = symbolintervalmapper14;
            this.m_Button12.TextHeight = 48;
            this.m_Button12.TextValue = 0D;
            this.m_Button12.TextWidth = 90;
            this.m_Button12.Top = 0;
            this.m_Button12.Value = 0D;
            this.m_Button12.VisibleDynamicsValue = true;
            this.m_Button12.VisualPropertiesHashCode = -1250412459;
            this.m_Button12.Width = 100;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "手動選擇";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_手動選擇 = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_手動選擇) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Button);
            this.DrawingPrimitives.Add(this.m_Button1);
            this.DrawingPrimitives.Add(this.m_Button2);
            this.DrawingPrimitives.Add(this.m_Button3);
            this.DrawingPrimitives.Add(this.m_Button4);
            this.DrawingPrimitives.Add(this.m_Button5);
            this.DrawingPrimitives.Add(this.m_Button6);
            this.DrawingPrimitives.Add(this.m_Button7);
            this.DrawingPrimitives.Add(this.m_Button8);
            this.DrawingPrimitives.Add(this.m_Button9);
            this.DrawingPrimitives.Add(this.m_Button10);
            this.DrawingPrimitives.Add(this.m_bPG_Main);
            this.DrawingPrimitives.Add(this.m_Button11);
            this.DrawingPrimitives.Add(this.m_Button12);
            ((System.ComponentModel.ISupportInitialize)(this.m_Button)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button9)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button10)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_bPG_Main)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button11)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Button12)).EndInit();
        }
        
        private void m_Button_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button", "Click", "Show Screen", "S1手動", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.S1手動.Show();
        }
        
        private void m_Button1_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button1", "Click", "Show Screen", "S5手動", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.S5手動.Show();
        }
        
        private void m_Button2_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button2", "Click", "Show Screen", "S9手動", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.S9手動.Show();
        }
        
        private void m_Button3_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button3", "Click", "Show Screen", "S2手動", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.S2手動.Show();
        }
        
        private void m_Button4_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button4", "Click", "Show Screen", "S6手動", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.S6手動.Show();
        }
        
        private void m_Button5_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button5", "Click", "Show Screen", "S10手動", "");
            Neo.ApplicationFramework.Generated.Globals.S10手動.Show();
        }
        
        private void m_Button6_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button6", "Click", "Show Screen", "S3手動", "");
            Neo.ApplicationFramework.Generated.Globals.S3手動.Show();
        }
        
        private void m_Button7_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button7", "Click", "Show Screen", "S7手動", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.S7手動.Show();
        }
        
        private void m_Button8_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button8", "Click", "Show Screen", "S11手動", "");
            Neo.ApplicationFramework.Generated.Globals.S11手動.Show();
        }
        
        private void m_Button9_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button9", "Click", "Show Screen", "S4手動", "");
            Neo.ApplicationFramework.Generated.Globals.S4手動.Show();
        }
        
        private void m_Button10_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button10", "Click", "Show Screen", "S8手動", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.S8手動.Show();
        }
        
        private void m_bPG_Main_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bPG_Main", "Click", "Show Screen", "主頁", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.主頁.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bPG_Main", "Click", "Set Tag", "Tags.AutoStatus", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.AutoStatus.SetTag();
        }
        
        private void m_Button11_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button11", "Click", "Show Screen", "手動選擇", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.手動選擇.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button11", "Click", "Reset Tag", "Tags.AutoStatus", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.AutoStatus.ResetTag();
        }
        
        private void m_Button12_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button12", "Click", "Show Screen", "測試", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.測試.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button12", "Click", "Set Tag", "Tags.AutoStatus", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.AutoStatus.SetTag();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(手動選擇));
            this.m_Button.Text = resources.GetText("手動選擇.Button.Text", "S1");
            this.m_Button1.Text = resources.GetText("手動選擇.Button1.Text", "S5");
            this.m_Button2.Text = resources.GetText("手動選擇.Button2.Text", "S9");
            this.m_Button3.Text = resources.GetText("手動選擇.Button3.Text", "S2");
            this.m_Button4.Text = resources.GetText("手動選擇.Button4.Text", "S6");
            this.m_Button5.Text = resources.GetText("手動選擇.Button5.Text", "S10");
            this.m_Button6.Text = resources.GetText("手動選擇.Button6.Text", "S3");
            this.m_Button7.Text = resources.GetText("手動選擇.Button7.Text", "S7");
            this.m_Button8.Text = resources.GetText("手動選擇.Button8.Text", "S11");
            this.m_Button9.Text = resources.GetText("手動選擇.Button9.Text", "S4");
            this.m_Button10.Text = resources.GetText("手動選擇.Button10.Text", "S8");
            this.m_bPG_Main.Text = resources.GetText("手動選擇.bPG_Main.Text", "主頁");
            this.m_Button11.Text = resources.GetText("手動選擇.Button11.Text", "手動");
            this.m_Button12.Text = resources.GetText("手動選擇.Button12.Text", "測試");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_手動選擇) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
        }
    }
}
