//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	public partial class LicenseRootComponent : Neo.ApplicationFramework.Tools.License.LicenseRootComponent
	{
		
		public LicenseRootComponent()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		private void InitializeComponent()
		{
			Neo.ApplicationFramework.Tools.License.PanelHardwareIdList panelhardwareidlist1 = new Neo.ApplicationFramework.Tools.License.PanelHardwareIdList();
			Neo.ApplicationFramework.Tools.License.PanelHardwareIdList panelhardwareidlist2 = new Neo.ApplicationFramework.Tools.License.PanelHardwareIdList();
			Neo.ApplicationFramework.Tools.License.PanelHardwareIdList panelhardwareidlist3 = new Neo.ApplicationFramework.Tools.License.PanelHardwareIdList();
			Neo.ApplicationFramework.Tools.License.PanelHardwareIdList panelhardwareidlist4 = new Neo.ApplicationFramework.Tools.License.PanelHardwareIdList();
			Neo.ApplicationFramework.Tools.License.PanelHardwareIdList panelhardwareidlist5 = new Neo.ApplicationFramework.Tools.License.PanelHardwareIdList();
			Neo.ApplicationFramework.Tools.License.PanelHardwareIdList panelhardwareidlist6 = new Neo.ApplicationFramework.Tools.License.PanelHardwareIdList();
			Neo.ApplicationFramework.Tools.License.PanelHardwareIdList panelhardwareidlist7 = new Neo.ApplicationFramework.Tools.License.PanelHardwareIdList();
			Neo.ApplicationFramework.Tools.License.PanelHardwareIdList panelhardwareidlist8 = new Neo.ApplicationFramework.Tools.License.PanelHardwareIdList();
			Neo.ApplicationFramework.Tools.License.PanelHardwareIdList panelhardwareidlist9 = new Neo.ApplicationFramework.Tools.License.PanelHardwareIdList();
			// 
			// LicenseRootComponent
			// 
			panelhardwareidlist1.IdList.Add(59);
			panelhardwareidlist1.IdList.Add(65);
			panelhardwareidlist1.IdList.Add(86);
			panelhardwareidlist2.IdList.Add(23);
			panelhardwareidlist2.IdList.Add(24);
			panelhardwareidlist2.IdList.Add(25);
			panelhardwareidlist2.IdList.Add(32);
			panelhardwareidlist2.IdList.Add(33);
			panelhardwareidlist2.IdList.Add(34);
			panelhardwareidlist2.IdList.Add(37);
			panelhardwareidlist3.IdList.Add(35);
			panelhardwareidlist3.IdList.Add(36);
			panelhardwareidlist4.IdList.Add(78);
			panelhardwareidlist4.IdList.Add(79);
			panelhardwareidlist4.IdList.Add(80);
			panelhardwareidlist5.IdList.Add(26);
			panelhardwareidlist5.IdList.Add(27);
			panelhardwareidlist5.IdList.Add(28);
			panelhardwareidlist5.IdList.Add(38);
			panelhardwareidlist5.IdList.Add(39);
			panelhardwareidlist5.IdList.Add(40);
			panelhardwareidlist5.IdList.Add(47);
			panelhardwareidlist5.IdList.Add(48);
			panelhardwareidlist5.IdList.Add(48);
			panelhardwareidlist6.IdList.Add(29);
			panelhardwareidlist6.IdList.Add(30);
			panelhardwareidlist6.IdList.Add(31);
			panelhardwareidlist7.IdList.Add(20);
			panelhardwareidlist7.IdList.Add(21);
			panelhardwareidlist7.IdList.Add(22);
			panelhardwareidlist8.IdList.Add(74);
			panelhardwareidlist9.IdList.Add(18);
			panelhardwareidlist9.IdList.Add(19);
			this.PanelHardwareIDs.Add(Neo.ApplicationFramework.Interfaces.PanelTypeGroup.TxF, panelhardwareidlist1);
			this.PanelHardwareIDs.Add(Neo.ApplicationFramework.Interfaces.PanelTypeGroup.TxA, panelhardwareidlist2);
			this.PanelHardwareIDs.Add(Neo.ApplicationFramework.Interfaces.PanelTypeGroup.TxE, panelhardwareidlist3);
			this.PanelHardwareIDs.Add(Neo.ApplicationFramework.Interfaces.PanelTypeGroup.TxF_2, panelhardwareidlist4);
			this.PanelHardwareIDs.Add(Neo.ApplicationFramework.Interfaces.PanelTypeGroup.TxB, panelhardwareidlist5);
			this.PanelHardwareIDs.Add(Neo.ApplicationFramework.Interfaces.PanelTypeGroup.TxC, panelhardwareidlist6);
			this.PanelHardwareIDs.Add(Neo.ApplicationFramework.Interfaces.PanelTypeGroup.TAx, panelhardwareidlist7);
			this.PanelHardwareIDs.Add(Neo.ApplicationFramework.Interfaces.PanelTypeGroup.PC, panelhardwareidlist8);
			this.PanelHardwareIDs.Add(Neo.ApplicationFramework.Interfaces.PanelTypeGroup.QTermAx, panelhardwareidlist9);
			this.ProductFamilyRegistryPath = "SOFTWARE\\Beijer Electronics AB\\iX Developer 2\\Install";
			this.ProjectPanelName = "iX T7F-2";
			this.ProjectPanelTypeGroup = Neo.ApplicationFramework.Interfaces.PanelTypeGroup.TxF_2;
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public override void ConnectDataBindings()
		{
			base.ConnectDataBindings();
		}
		
		private void InitializeObjectCreations()
		{
		}
		
		private void InitializeBeginInits()
		{
		}
		
		private void InitializeEndInits()
		{
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(LicenseRootComponent));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected override void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
			base.ApplyLanguage();
		}
	}
}
