//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class 時間設定 : Neo.ApplicationFramework.Controls.Controls.Form {
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_bPG_TimeSetting;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_bPG_Main;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_bPG_Seat;
        
        private Neo.ApplicationFramework.Controls.Controls.Button m_bPG_Tray;
        
        private bool m_Initialized_時間設定;
        
        public 時間設定() {
            this.InitializeComponent();
            this.m_bPG_TimeSetting.Click += new System.EventHandler(this.m_bPG_TimeSetting_Action_Click);
            this.m_bPG_Main.Click += new System.EventHandler(this.m_bPG_Main_Action_Click);
            this.m_bPG_Seat.Click += new System.EventHandler(this.m_bPG_Seat_Action_Click);
            this.m_bPG_Tray.Click += new System.EventHandler(this.m_bPG_Tray_Action_Click);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter bPG_TimeSetting {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_bPG_TimeSetting);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter bPG_Main {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_bPG_Main);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter bPG_Seat {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_bPG_Seat);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter bPG_Tray {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonCFAdapter>(this.m_bPG_Tray);
            }
        }
        
        private void InitializeComponent() {
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper1 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper2 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper3 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper symbolintervalmapper4 = new Neo.ApplicationFramework.Common.Dynamics.SymbolIntervalMapper();
            this.m_Rectangle = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_bPG_TimeSetting = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_bPG_Main = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_bPG_Seat = new Neo.ApplicationFramework.Controls.Controls.Button();
            this.m_bPG_Tray = new Neo.ApplicationFramework.Controls.Controls.Button();
            ((System.ComponentModel.ISupportInitialize)(this.m_bPG_TimeSetting)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_bPG_Main)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_bPG_Seat)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_bPG_Tray)).BeginInit();
            this.SuspendLayout();
            // 
            // 時間設定
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.SingleBorder;
            this.ControlBox = false;
            // 
            // m_Rectangle
            // 
            this.m_Rectangle.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle.BlinkDynamicsValue = false;
            this.m_Rectangle.EnabledDynamicsValue = true;
            this.m_Rectangle.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.Height = 410;
            this.m_Rectangle.Left = 0;
            this.m_Rectangle.Name = "m_Rectangle";
            this.m_Rectangle.ScreenOwnerName = "時間設定";
            this.m_Rectangle.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.Top = 71;
            this.m_Rectangle.VisibleDynamicsValue = true;
            this.m_Rectangle.Width = 800;
            // 
            // m_bPG_TimeSetting
            // 
            this.m_bPG_TimeSetting.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(157)))), ((int)(((byte)(218)))), ((int)(((byte)(78))))), System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(177)))), ((int)(((byte)(76))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_bPG_TimeSetting.BlinkDynamicsValue = false;
            this.m_bPG_TimeSetting.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_bPG_TimeSetting.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_bPG_TimeSetting.EnabledDynamicsValue = true;
            this.m_bPG_TimeSetting.FontFamily = "新細明體";
            this.m_bPG_TimeSetting.FontSizePixels = 20;
            this.m_bPG_TimeSetting.ForceTransparency = true;
            this.m_bPG_TimeSetting.Height = 70;
            this.m_bPG_TimeSetting.IndicatorMargin = null;
            this.m_bPG_TimeSetting.Left = 306;
            this.m_bPG_TimeSetting.Name = "m_bPG_TimeSetting";
            this.m_bPG_TimeSetting.RequiresTransparency = true;
            this.m_bPG_TimeSetting.ScreenOwnerName = "時間設定";
            this.m_bPG_TimeSetting.SymbolIntervalMapper = symbolintervalmapper1;
            this.m_bPG_TimeSetting.TextHeight = 24;
            this.m_bPG_TimeSetting.TextValue = 0D;
            this.m_bPG_TimeSetting.TextWidth = 90;
            this.m_bPG_TimeSetting.Top = 0;
            this.m_bPG_TimeSetting.Value = 0D;
            this.m_bPG_TimeSetting.VisibleDynamicsValue = true;
            this.m_bPG_TimeSetting.VisualPropertiesHashCode = 509671045;
            this.m_bPG_TimeSetting.Width = 100;
            // 
            // m_bPG_Main
            // 
            this.m_bPG_Main.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_bPG_Main.BlinkDynamicsValue = false;
            this.m_bPG_Main.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_bPG_Main.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_bPG_Main.EnabledDynamicsValue = true;
            this.m_bPG_Main.FontFamily = "新細明體";
            this.m_bPG_Main.FontSizePixels = 30;
            this.m_bPG_Main.ForceTransparency = true;
            this.m_bPG_Main.Height = 70;
            this.m_bPG_Main.IndicatorMargin = null;
            this.m_bPG_Main.Left = 0;
            this.m_bPG_Main.Name = "m_bPG_Main";
            this.m_bPG_Main.RequiresTransparency = true;
            this.m_bPG_Main.ScreenOwnerName = "時間設定";
            this.m_bPG_Main.SymbolIntervalMapper = symbolintervalmapper2;
            this.m_bPG_Main.TextHeight = 36;
            this.m_bPG_Main.TextValue = 0D;
            this.m_bPG_Main.TextWidth = 90;
            this.m_bPG_Main.Top = 0;
            this.m_bPG_Main.Value = 0D;
            this.m_bPG_Main.VisibleDynamicsValue = true;
            this.m_bPG_Main.VisualPropertiesHashCode = 509671045;
            this.m_bPG_Main.Width = 100;
            // 
            // m_bPG_Seat
            // 
            this.m_bPG_Seat.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_bPG_Seat.BlinkDynamicsValue = false;
            this.m_bPG_Seat.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_bPG_Seat.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_bPG_Seat.EnabledDynamicsValue = true;
            this.m_bPG_Seat.FontFamily = "新細明體";
            this.m_bPG_Seat.FontSizePixels = 20;
            this.m_bPG_Seat.ForceTransparency = true;
            this.m_bPG_Seat.Height = 70;
            this.m_bPG_Seat.IndicatorMargin = null;
            this.m_bPG_Seat.Left = 102;
            this.m_bPG_Seat.Name = "m_bPG_Seat";
            this.m_bPG_Seat.RequiresTransparency = true;
            this.m_bPG_Seat.ScreenOwnerName = "時間設定";
            this.m_bPG_Seat.SymbolIntervalMapper = symbolintervalmapper3;
            this.m_bPG_Seat.TextHeight = 24;
            this.m_bPG_Seat.TextValue = 0D;
            this.m_bPG_Seat.TextWidth = 90;
            this.m_bPG_Seat.Top = 0;
            this.m_bPG_Seat.Value = 0D;
            this.m_bPG_Seat.VisibleDynamicsValue = true;
            this.m_bPG_Seat.VisualPropertiesHashCode = 509671045;
            this.m_bPG_Seat.Width = 100;
            // 
            // m_bPG_Tray
            // 
            this.m_bPG_Tray.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalTopToBottom);
            this.m_bPG_Tray.BlinkDynamicsValue = false;
            this.m_bPG_Tray.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(112)))), ((int)(((byte)(112))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_bPG_Tray.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_bPG_Tray.EnabledDynamicsValue = true;
            this.m_bPG_Tray.FontFamily = "新細明體";
            this.m_bPG_Tray.FontSizePixels = 20;
            this.m_bPG_Tray.ForceTransparency = true;
            this.m_bPG_Tray.Height = 70;
            this.m_bPG_Tray.IndicatorMargin = null;
            this.m_bPG_Tray.Left = 204;
            this.m_bPG_Tray.Name = "m_bPG_Tray";
            this.m_bPG_Tray.RequiresTransparency = true;
            this.m_bPG_Tray.ScreenOwnerName = "時間設定";
            this.m_bPG_Tray.SymbolIntervalMapper = symbolintervalmapper4;
            this.m_bPG_Tray.TextHeight = 24;
            this.m_bPG_Tray.TextValue = 0D;
            this.m_bPG_Tray.TextWidth = 90;
            this.m_bPG_Tray.Top = 0;
            this.m_bPG_Tray.Value = 0D;
            this.m_bPG_Tray.VisibleDynamicsValue = true;
            this.m_bPG_Tray.VisualPropertiesHashCode = 509671045;
            this.m_bPG_Tray.Width = 100;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "時間設定";
            this.PopupScreen = false;
            this.ScreenID = null;
            this.ScreenTitle = "";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_時間設定 = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_時間設定) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Rectangle);
            this.DrawingPrimitives.Add(this.m_bPG_TimeSetting);
            this.DrawingPrimitives.Add(this.m_bPG_Main);
            this.DrawingPrimitives.Add(this.m_bPG_Seat);
            this.DrawingPrimitives.Add(this.m_bPG_Tray);
            ((System.ComponentModel.ISupportInitialize)(this.m_bPG_TimeSetting)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_bPG_Main)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_bPG_Seat)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_bPG_Tray)).EndInit();
        }
        
        private void m_bPG_TimeSetting_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bPG_TimeSetting", "Click", "Show Screen", "時間設定", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.時間設定.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bPG_TimeSetting", "Click", "Reset Tag", "Tags.AutoStatus", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.AutoStatus.ResetTag();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bPG_TimeSetting", "Click", "Set Tag", "Tags.ManualStatus", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.ManualStatus.SetTag();
        }
        
        private void m_bPG_Main_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bPG_Main", "Click", "Show Screen", "主頁", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.主頁.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bPG_Main", "Click", "Reset Tag", "Tags.ManualStatus", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.ManualStatus.ResetTag();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bPG_Main", "Click", "Set Tag", "Tags.AutoStatus", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.AutoStatus.SetTag();
        }
        
        private void m_bPG_Seat_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bPG_Seat", "Click", "Show Screen", "手動_取放料", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.手動_取放料.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bPG_Seat", "Click", "Reset Tag", "Tags.AutoStatus", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.AutoStatus.ResetTag();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bPG_Seat", "Click", "Set Tag", "Tags.ManualStatus", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.ManualStatus.SetTag();
        }
        
        private void m_bPG_Tray_Action_Click(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bPG_Tray", "Click", "Show Screen", "手動_取放盤", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.手動_取放盤.Show();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bPG_Tray", "Click", "Reset Tag", "Tags.AutoStatus", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.AutoStatus.ResetTag();
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_bPG_Tray", "Click", "Set Tag", "Tags.ManualStatus", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.ManualStatus.SetTag();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(時間設定));
            this.m_bPG_TimeSetting.Text = resources.GetText("時間設定.bPG_TimeSetting.Text", "時間設定");
            this.m_bPG_Main.Text = resources.GetText("時間設定.bPG_Main.Text", "主頁");
            this.m_bPG_Seat.Text = resources.GetText("時間設定.bPG_Seat.Text", "取放中座");
            this.m_bPG_Tray.Text = resources.GetText("時間設定.bPG_Tray.Text", "取放料盤");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_時間設定) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
        }
    }
}
